/**
 * @file sf_core_providers.h
 * @brief C ABI for registering a host-owned backend with the Snowflake driver
 *        core.
 *
 * A host that owns the transport — notably Snowflake's execution platform (XP),
 * whose stored-procedure sandbox has no outbound network and must send queries
 * over its existing gRPC channel — implements the callbacks below and installs
 * them with sf_core_register_xp_backend().
 *
 * Selection is a runtime decision: set SNOWFLAKE_RUNNING_INSIDE_XP (any
 * value, including empty) before constructing the driver. Presence enables
 * XP mode; registering without it is accepted but has no effect. See
 * src/xp_backend/mod.rs.
 *
 * The symbols are exported from whichever shared object embeds sf_core —
 * sf_core_python.*.so, libjdbc_bridge.so, libsfodbc.so, libnodejs_bridge.so —
 * so a host must resolve them from the library it actually loaded. On Linux,
 * dlopen that file with RTLD_NOLOAD | RTLD_GLOBAL and dlsym from the resulting
 * handle; each library holds its own copy of the registry, so registering into
 * the wrong one silently does nothing.
 *
 * Memory ownership:
 *   - Strings a callback writes to a *_out parameter, and
 *     SfCoreFfiError.message, are allocated by the host (strdup or malloc) and
 *     freed by the driver.
 *   - Strings the driver returns (sf_core_get_version) must be freed by the
 *     host with sf_core_free_string(), never with free().
 *
 * Callback contract:
 *   - Callbacks may run concurrently on several threads, so `context` must be
 *     thread-safe and must outlive the process's use of the driver.
 *   - Callbacks run on Tokio's blocking thread pool.
 *   - A callback must not let a C++ exception escape. Rust cannot unwind
 *     through extern "C" and the process will abort. Catch at the boundary and
 *     report through SfCoreFfiError instead.
 *   - Return 0 on success, non-zero on failure. Set SfCoreFfiError.code to a
 *     Snowflake server error code where one exists, so it reaches the user
 *     unchanged.
 *
 * JSON payloads
 * =============
 *
 * Callback JSON schemas are defined by XpQueryRequest, XpCancelRequest,
 * XpCancelResponse, XpAuthRequest, and XpSessionInfo in
 * src/xp_backend/ffi.rs. Their serialization tests provide current examples.
 * Absent optional fields are omitted rather than sent as null; hosts should
 * ignore unknown fields.
 *
 * This file is generated by cbindgen. Do not edit manually — run
 * scripts/generate_providers_header.sh.
 */

#ifndef SF_CORE_PROVIDERS_H
#define SF_CORE_PROVIDERS_H

/* Warning: autogenerated by cbindgen. Regenerate with scripts/generate_providers_header.sh instead of editing. */

#include <stdint.h>
#include <stddef.h>

/**
 * Bump on any change to [`XpBackendCallbacks`]'s layout or a callback signature.
 * A mismatched host is rejected at registration, so a layout mismatch is an
 * error message rather than undefined behaviour.
 */
#define XP_BACKEND_ABI_VERSION 1

/**
 * `message` is host-allocated and freed by the driver. `code` should be a
 * Snowflake server error code where the host has one, so it survives to the user
 * unchanged.
 */
typedef struct SfCoreFfiError {
    int32_t code;
    /**
     * NUL-terminated message, or null when the host has nothing to add.
     */
    char *message;
} SfCoreFfiError;

/**
 * One struct so registration is atomic: there is no way to install a query
 * executor without also providing authentication.
 *
 * `abi_version` and `struct_size` come first and must be set to
 * [`XP_BACKEND_ABI_VERSION`] and `sizeof(XpBackendCallbacks)`, so the driver can
 * reject a mismatched host instead of reading past the end of a struct laid out
 * differently.
 */
typedef struct XpBackendCallbacks {
    uint32_t abi_version;
    uintptr_t struct_size;
    /**
     * Opaque host state, passed back to every callback. Must be thread-safe
     * and must outlive the process's use of the driver.
     */
    void *context;
    int32_t (*execute_query)(void *ctx, const char *sql, const char *params_json, char **result_out, struct SfCoreFfiError *error_out);
    int32_t (*get_query_status)(void *ctx, const char *query_id, char **result_out, struct SfCoreFfiError *error_out);
    int32_t (*cancel_query)(void *ctx, const char *params_json, char **result_out, struct SfCoreFfiError *error_out);
    int32_t (*get_query_result)(void *ctx, const char *query_id, char **result_out, struct SfCoreFfiError *error_out);
    int32_t (*authenticate)(void *ctx, const char *params_json, char **result_out, struct SfCoreFfiError *error_out);
    int32_t (*get_session_parameters)(void *ctx, char **result_out, struct SfCoreFfiError *error_out);
    int32_t (*upload_stream)(void *ctx, const char *destination, const uint8_t *data, uintptr_t data_len, const char *metadata_json, char **result_out, struct SfCoreFfiError *error_out);
    int32_t (*download_stream)(void *ctx, const char *source, const char *metadata_json, uint8_t **data_out, uintptr_t *data_len_out, struct SfCoreFfiError *error_out);
    int32_t (*list_stage_files)(void *ctx, const char *stage_location, int32_t is_exact_match, char **result_out, struct SfCoreFfiError *error_out);
} XpBackendCallbacks;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Returns `0`, or a negative [`error_codes`] value.
 *
 * # Safety
 *
 * `callbacks` must point to readable storage containing the `abi_version` and
 * `struct_size` prefix. When those values match this build, it must point to a
 * valid `XpBackendCallbacks`, with `context` and every non-null function
 * pointer remaining valid for as long as the process uses the driver.
 */
int32_t sf_core_register_xp_backend(const struct XpBackendCallbacks *callbacks);

/**
 * Always `1`. Lets a host tell "driver too old to know about backends" (symbol
 * absent, `dlsym` fails) from "backends supported", without parsing a version.
 */
int32_t sf_core_xp_backend_is_available(void);

/**
 * Returns `0`. The caller **must** release the string with
 * [`sf_core_free_string`].
 *
 * # Safety
 *
 * `version_out` must be a valid, writable pointer to a `*mut c_char`.
 */
int32_t sf_core_get_version(char **version_out);

/**
 * Free a string the driver allocated. No-op on null.
 *
 * # Safety
 *
 * `ptr` must be null or a not-yet-freed pointer returned by an `sf_core`
 * function. A host-allocated pointer is undefined behaviour: the allocators
 * differ.
 */
void sf_core_free_string(char *ptr);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* SF_CORE_PROVIDERS_H */
