#![allow(clippy::result_large_err)]
mod alter_session_parser;
pub mod async_query_registry;
pub mod connection;
mod database;
pub(crate) mod error;
pub(crate) mod global_state;
pub mod logout_decision;
pub(crate) mod query;
mod session_parameters;
pub mod statement;

pub use crate::config::settings::Setting;
pub use crate::handle_manager::Handle;
pub use async_query_registry::AsyncQueryRegistry;
pub use connection::Connection;
pub use connection::ConnectionInfo;
pub use connection::QueryStatus;
pub use connection::QueryStatusInfo;
pub use connection::RefreshContext;
pub use connection::connection_close;
pub use connection::connection_fetch_async_results;
pub use connection::connection_get_info;
pub use connection::connection_get_query_status;
pub use connection::connection_init;
pub use connection::connection_is_closed;
pub use connection::connection_new;
pub use connection::connection_release;
pub use connection::connection_set_option;
pub use connection::connection_set_session_parameters;
pub use connection::with_valid_session;
pub use database::database_init;
pub use database::database_new;
pub use database::database_release;
pub use database::database_set_option;
pub use error::ApiError;
pub use session_parameters::connection_get_parameter;
pub use statement::statement_bind;
pub use statement::statement_execute_async;
pub use statement::statement_execute_query;
pub use statement::statement_new;
pub use statement::statement_prepare;
pub use statement::statement_release;
pub use statement::statement_set_option;
pub use statement::statement_set_sql_query;
pub use statement::{BindingType, ColumnMetadata, DataPtr, calculate_rows_affected};
