#!/usr/bin/env python3
"""Generate or verify .mirror/manifest.txt.

The manifest is the sorted list of files `copybara migrate copy.bara.sky mirror`
would push to the public mirror, followed by a sha256 of that list. CI
(validations.yml::mirror-manifest) fails any PR whose actual mirrored
file-set has drifted from the checked-in manifest, so every change to
what reaches the mirror becomes an explicit reviewable diff.

Usage:
    scripts/mirror/generate_manifest.py           # rewrite the manifest in place
    scripts/mirror/generate_manifest.py --check   # fail (non-zero) on drift

EXCLUDED_PATHS is parsed out of copy.bara.sky so that file stays the
single source of truth. Matching follows the subset of Copybara's glob
semantics we actually use:

  - `<prefix>/**`           matches any path starting with `<prefix>/`
  - `**/<rest>`             matches `<rest>` at any depth
  - `<literal>`             matches exactly one path
  - `<a>*<b>`               `*` matches within a single path component

This is intentionally narrower than full gitignore/pathspec semantics.
If you add a new pattern to EXCLUDED_PATHS and the generator rejects it,
extend `_pattern_to_regex` below rather than silently accepting a
pattern the generator can't evaluate.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
CONFIG_PATH = REPO_ROOT / "copy.bara.sky"
MANIFEST_PATH = REPO_ROOT / ".mirror" / "manifest.txt"

MANIFEST_HEADER = """\
# Auto-generated by scripts/mirror/generate_manifest.py.
# Do not edit by hand; re-run the generator and commit the result.
#
# Every path below is a file that `copybara migrate copy.bara.sky mirror`
# would push to snowflakedb/ud-mirror-test. Any PR that
# changes this set must include the regenerated manifest in the same diff
# (enforced by validations.yml::mirror-manifest). The trailing
# `# sha256:` line hashes the sorted paths for tamper-evidence.
"""


def _parse_excluded_paths(config_text: str) -> list[str]:
    """Extract EXCLUDED_PATHS = [...] from copy.bara.sky.

    Deliberately simple regex rather than a Starlark parser — the list is
    a flat sequence of string literals interspersed with comments.
    """
    match = re.search(
        r"EXCLUDED_PATHS\s*=\s*\[(?P<body>.*?)\]",
        config_text,
        re.DOTALL,
    )
    if match is None:
        raise RuntimeError(
            "Could not locate `EXCLUDED_PATHS = [...]` in copy.bara.sky. "
            "The denylist block must be a single list literal."
        )

    body = match.group("body")
    # Strip line comments before parsing so `# note` inside the list is ignored.
    body = re.sub(r"#[^\n]*", "", body)
    patterns = re.findall(r'"([^"]+)"', body)
    if not patterns:
        raise RuntimeError(
            "EXCLUDED_PATHS parsed as empty. Check copy.bara.sky formatting."
        )
    return patterns


def _pattern_to_regex(pattern: str) -> re.Pattern[str]:
    """Translate one Copybara glob pattern to a regex.

    Supported forms:
      foo/**        -> everything under foo/
      **/foo        -> foo at any depth
      **/*bar*      -> any file whose basename contains bar, anywhere
      foo/bar       -> exactly foo/bar
      *.ext         -> files with that extension (at root)
      foo/*.ext     -> files with that extension (one level deep)
    """
    if "***" in pattern or pattern.startswith("/"):
        raise ValueError(
            f"Unsupported glob pattern {pattern!r}. Extend _pattern_to_regex "
            "in scripts/mirror/generate_manifest.py if you need this shape."
        )

    # Tokenize, handling `**` before `*` so the single-star case can't
    # accidentally consume a doublestar.
    out: list[str] = []
    i = 0
    while i < len(pattern):
        ch = pattern[i]
        if pattern.startswith("**/", i):
            out.append("(?:.*/)?")
            i += 3
        elif pattern.startswith("/**", i):
            # `/foo/**` - match the slash and everything beneath (including nothing)
            out.append("(?:/.*)?")
            i += 3
        elif pattern.startswith("**", i):
            out.append(".*")
            i += 2
        elif ch == "*":
            # Single star: match within one path component.
            out.append("[^/]*")
            i += 1
        elif ch == "?":
            out.append("[^/]")
            i += 1
        elif ch in ".+^$()|{}[]\\":
            out.append(re.escape(ch))
            i += 1
        else:
            out.append(ch)
            i += 1

    return re.compile("^" + "".join(out) + "$")


def _git_tracked_files() -> list[str]:
    """List repo-tracked files relative to REPO_ROOT.

    Using `git ls-files` mirrors Copybara's git-origin view — untracked
    and gitignored files never reach the mirror, so they shouldn't appear
    in the manifest either.
    """
    result = subprocess.run(
        ["git", "-C", str(REPO_ROOT), "ls-files", "-z"],
        check=True,
        capture_output=True,
    )
    return [p for p in result.stdout.decode().split("\0") if p]


def _compute_mirrored_paths(
    all_paths: list[str], excluded_patterns: list[str]
) -> list[str]:
    regexes = [_pattern_to_regex(p) for p in excluded_patterns]
    kept: list[str] = []
    for path in all_paths:
        if any(r.match(path) for r in regexes):
            continue
        kept.append(path)
    kept.sort()
    return kept


def _render_manifest(paths: list[str]) -> str:
    body = "\n".join(paths)
    digest = hashlib.sha256(body.encode()).hexdigest()
    return f"{MANIFEST_HEADER}\n{body}\n# sha256: {digest}\n"


def _regenerate() -> str:
    config_text = CONFIG_PATH.read_text()
    excluded = _parse_excluded_paths(config_text)
    tracked = _git_tracked_files()
    mirrored = _compute_mirrored_paths(tracked, excluded)
    return _render_manifest(mirrored)


_PURPOSE_BANNER = """\
==============================================================================
  MIRROR MANIFEST CHECK FAILED

  Purpose:  .mirror/manifest.txt pins the exact set of files that Copybara
            would push to the public mirror. Keeping it in sync with the
            repo forces every PR that changes what reaches the mirror to
            include an explicit manifest diff a reviewer has to approve —
            that's the security gate against accidentally exposing
            internal files.
==============================================================================
"""

_FIX_INSTRUCTIONS = """\
How to fix
----------
  1. If the change above is intentional (the added files really should be
     mirrored), regenerate and commit the manifest:

         python scripts/mirror/generate_manifest.py
         git add .mirror/manifest.txt

  2. If the added files should NOT be mirrored, move them under
     `_internal/` (or add a pattern to EXCLUDED_PATHS in copy.bara.sky),
     then regenerate as above.
"""


def _parse_manifest_paths(text: str) -> list[str]:
    """Return the sorted path list from a rendered manifest, ignoring
    the header block and the trailing `# sha256:` line."""
    return [
        line
        for line in text.splitlines()
        if line and not line.startswith("#")
    ]


def _format_change_report(current_paths: list[str], expected_paths: list[str]) -> str:
    current_set = set(current_paths)
    expected_set = set(expected_paths)
    added = sorted(expected_set - current_set)
    removed = sorted(current_set - expected_set)

    lines: list[str] = ["What changed", "------------"]

    if added:
        lines.append(f"Files that would now reach the mirror (+{len(added)}):")
        for p in added:
            lines.append(f"  + {p}")
    if removed:
        if added:
            lines.append("")
        lines.append(f"Files no longer reaching the mirror (-{len(removed)}):")
        for p in removed:
            lines.append(f"  - {p}")

    if not added and not removed:
        # Content is identical path-for-path but the rendered text still
        # differs — header or hash was hand-edited.
        lines.append(
            "Manifest paths match, but the file header or sha256 line was "
            "edited by hand. Regenerate to restore the canonical form."
        )

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if the checked-in manifest is out of date.",
    )
    args = parser.parse_args()

    rendered = _regenerate()

    if args.check:
        if not MANIFEST_PATH.exists():
            sys.stderr.write(_PURPOSE_BANNER)
            sys.stderr.write(
                "\n.mirror/manifest.txt does not exist.\n\n"
                + _FIX_INSTRUCTIONS
            )
            return 1
        current = MANIFEST_PATH.read_text()
        if current != rendered:
            current_paths = _parse_manifest_paths(current)
            expected_paths = _parse_manifest_paths(rendered)
            sys.stderr.write(_PURPOSE_BANNER)
            sys.stderr.write("\n")
            sys.stderr.write(_format_change_report(current_paths, expected_paths))
            sys.stderr.write("\n")
            sys.stderr.write(_FIX_INSTRUCTIONS)
            return 1
        return 0

    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(rendered)
    print(f"Wrote {MANIFEST_PATH.relative_to(REPO_ROOT)}", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
