#!/usr/bin/env python3
"""Write ci/mirroring/import_paths.bara.sky scoped to a mirror PR's changed files.

Copybara merge-import reconciles every managed path when baseline flags are
set. Limiting origin_files/destination_files to the PR's actual diff keeps
the internal import PR aligned with the mirror PR (e.g. 9 files, not 14).
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import subprocess
import sys
from pathlib import Path

MIRROR_REPO = "snowflakedb/drivers"
OUTPUT = Path(__file__).resolve().parents[2] / "ci" / "mirroring" / "import_paths.bara.sky"

# Keep in sync with ci/mirroring/copy.bara.sky.
NOMIRROR_PATHS = [
    "NOMIRROR/**",
    "**/NOMIRROR/**",
]
EXCLUDED_PATHS = NOMIRROR_PATHS + [
    ".ai/**",
    ".cursor/**",
    ".claude/**",
    ".buildkite/**",
    ".ci/**",
    ".github/**",
    "ci/**",
    "scripts/**",
    "shell.nix",
]
EXCLUDED_PATH_OVERRIDES = [
    ".github/workflows/close-imported-pr.yml",
    ".github/workflows/pre-commit.yml",
    ".github/workflows/validations.yml",
    ".github/actions/cargo-cache/action.yml",
    ".github/workflows/mirror-test-rust-core.yml",
    ".github/workflows/mirror-test-odbc.yml",
    ".github/workflows/mirror-test-python.yml",
    ".github/actions/setup-odbc-build-env/action.yml",
]


def _matches_any(path: str, patterns: list[str]) -> bool:
    return any(fnmatch.fnmatch(path, pattern) for pattern in patterns)


def is_mirrored_path(path: str) -> bool:
    if _matches_any(path, NOMIRROR_PATHS):
        return False
    if _matches_any(path, EXCLUDED_PATH_OVERRIDES):
        return True
    if _matches_any(path, EXCLUDED_PATHS):
        return False
    return True


def fetch_pr_files(pr_number: str) -> list[str]:
    return subprocess.check_output(
        [
            "gh",
            "api",
            f"repos/{MIRROR_REPO}/pulls/{pr_number}/files",
            "--paginate",
            "--jq",
            ".[].filename",
        ],
        text=True,
    ).splitlines()


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Write ci/mirroring/import_paths.bara.sky for a mirror PR import.",
    )
    parser.add_argument("pr_number", help="Mirror pull request number")
    parser.add_argument(
        "--draft",
        action="store_true",
        help="Open the imported internal PR as a draft",
    )
    args = parser.parse_args()

    pr_files = fetch_pr_files(args.pr_number)
    mirrored = [path for path in pr_files if is_mirrored_path(path)]
    dropped = sorted(set(pr_files) - set(mirrored))

    if dropped:
        print(
            "Skipping paths outside the mirrored tree:",
            ", ".join(dropped),
            file=sys.stderr,
        )
    if not mirrored:
        print("No mirrored files to import from mirror PR", file=sys.stderr)
        sys.exit(1)

    OUTPUT.write_text(
        "# Generated by scripts/mirror/prepare_import_paths.py — do not edit.\n"
        f"IMPORT_FILE_GLOBS = {json.dumps(mirrored, indent=4)}\n"
        f"IMPORT_AS_DRAFT = {args.draft}\n",
        encoding="utf-8",
    )
    print(f"Import scoped to {len(mirrored)} file(s):", ", ".join(mirrored), file=sys.stderr)
    if args.draft:
        print("Imported internal PR will be opened as a draft", file=sys.stderr)


if __name__ == "__main__":
    main()
