//! Procedural macros for the `odbc` crate.
//!
//! Currently provides one derive — [`ClassifyError`] — that lets an error
//! enum carry its in-band-telemetry classification inline on each variant
//! using a strongly-typed enum value rather than a stringly-typed strum
//! prop. See the derive's docs for the attribute syntax and codegen
//! contract.

use proc_macro::TokenStream;
use proc_macro2::Span;
use quote::quote;
use syn::{Attribute, Data, DeriveInput, Fields, Ident, parse_macro_input};

const ATTR_NAME: &str = "error_source";
const FALLBACK_VARIANT: &str = "Unknown";

/// Derive macro that generates `fn error_source(&self) -> ErrorSource` on
/// the target enum, picking each variant's `ErrorSource` value from a
/// per-variant `#[error_source(<Variant>)]` helper attribute.
///
/// # Example
///
/// ```ignore
/// #[derive(ClassifyError)]
/// pub enum OdbcError {
///     #[error_source(ApiMisuse)]
///     InvalidHandle { /* ... */ },
///
///     // No attribute => generated arm uses ErrorSource::Unknown.
///     OperationCanceled { /* ... */ },
/// }
/// ```
///
/// # Codegen
///
/// The generated impl is, schematically:
///
/// ```ignore
/// impl OdbcError {
///     pub fn error_source(&self) -> ErrorSource {
///         match self {
///             Self::InvalidHandle { .. } => ErrorSource::ApiMisuse,
///             Self::OperationCanceled { .. } => ErrorSource::Unknown,
///             // ...
///         }
///     }
/// }
/// ```
///
/// # Assumptions
///
/// - The target enum must be in scope alongside an `ErrorSource` enum
///   that has unit-like variants matching every name used in the
///   `#[error_source(...)]` attributes (plus an `Unknown` variant for
///   the fallback).
/// - The attribute argument is parsed as a single [`syn::Ident`]; paths
///   like `crate::api::error::ErrorSource::ApiMisuse` are *not* accepted.
///   Use a bare variant name instead.
#[proc_macro_derive(ClassifyError, attributes(error_source))]
pub fn classify_error_derive(input: TokenStream) -> TokenStream {
    let input = parse_macro_input!(input as DeriveInput);
    match classify_error_derive_inner(&input) {
        Ok(tokens) => tokens,
        Err(err) => err.to_compile_error().into(),
    }
}

fn classify_error_derive_inner(input: &DeriveInput) -> syn::Result<TokenStream> {
    let enum_name = &input.ident;

    let variants = match &input.data {
        Data::Enum(data_enum) => &data_enum.variants,
        _ => {
            return Err(syn::Error::new_spanned(
                enum_name,
                "ClassifyError can only be derived for enums",
            ));
        }
    };

    let fallback = Ident::new(FALLBACK_VARIANT, Span::call_site());
    let mut match_arms = Vec::with_capacity(variants.len());

    for variant in variants {
        let variant_name = &variant.ident;

        let pattern = match &variant.fields {
            Fields::Named(_) => quote! { Self::#variant_name { .. } },
            Fields::Unnamed(_) => quote! { Self::#variant_name(..) },
            Fields::Unit => quote! { Self::#variant_name },
        };

        let bucket = parse_error_source_attr(&variant.attrs)?.unwrap_or_else(|| fallback.clone());

        match_arms.push(quote! {
            #pattern => ErrorSource::#bucket,
        });
    }

    let expanded = quote! {
        impl #enum_name {
            /// High-level [`ErrorSource`] bucket reported in the in-band
            /// telemetry `exception` event.
            ///
            /// Generated by `#[derive(ClassifyError)]`. Variants are
            /// classified by their `#[error_source(<Variant>)]`
            /// attribute; variants without one fall back to
            /// [`ErrorSource::Unknown`].
            pub fn error_source(&self) -> ErrorSource {
                match self {
                    #( #match_arms )*
                }
            }
        }
    };

    Ok(TokenStream::from(expanded))
}

fn parse_error_source_attr(attrs: &[Attribute]) -> syn::Result<Option<Ident>> {
    let mut found: Option<Ident> = None;
    for attr in attrs {
        if !attr.path().is_ident(ATTR_NAME) {
            continue;
        }
        if found.is_some() {
            return Err(syn::Error::new_spanned(
                attr,
                "duplicate `#[error_source(...)]` attribute on variant",
            ));
        }
        let ident: Ident = attr.parse_args().map_err(|e| {
            syn::Error::new(
                e.span(),
                "`#[error_source(...)]` expects a single bare ErrorSource variant ident, \
                 e.g. `#[error_source(ApiMisuse)]`",
            )
        })?;
        found = Some(ident);
    }
    Ok(found)
}
