[pytest]
addopts = -q
testpaths = tests
markers =
  reference: candidate to run in comparison (use on curated tests if you want a small PR set)
  skip_reference(reason: str = ''): skip when --connector=reference
  skip_universal(reason: str = ''): skip when --connector=universal
  skip_old_driver_until(version: str = None, date: str = None, reason: str = ''): reserved for future

[tox]
requires = tox-uv>=1.8
env_list =
  lint, type,
  py{39,310,311,312,313}-unit,
  py{39,310,311,312,313}-integ-universal,
  py{39,310,311,312,313}-integ-reference

[testenv]
passenv = *
deps = .[dev]
commands = pytest -q {posargs}

[testenv:py{39,310,311,312,313}-unit]
commands = pytest tests/unit -n auto --maxfail=1

[testenv:py{39,310,311,312,313}-integ-universal]
commands = pytest -n auto --maxfail=1 --connector=universal {posargs}

[testenv:py{39,310,311,312,313}-integ-reference]
commands =
  uv pip install "snowflake-connector-python=={env:REF_VERSION:3.10.1}"
  pytest -n auto --maxfail=1 --connector=reference {posargs}
