"""Auto-generated from PARAM_DEFS in sf_core. DO NOT EDIT.

Regenerated by the generate-connection-config pre-commit hook whenever
param_registry.rs changes.  Any manual changes will be silently overwritten.

This file intentionally contains only information derivable from
``PARAM_DEFS``: the dataclass fields and the ``_ALIAS_MAP`` /
``_PYTHON_TO_RUST_NAME`` / ``_SENSITIVE_PARAMS`` lookup tables.  Behavioural
helpers (``from_kwargs``, ``to_options``, ``to_proto_options``, legacy
rewrites, application validation, Python-only fields) live in
:mod:`snowflake.connector._internal.connection_config_mixin` and are inherited
via :class:`ConnectionConfigMixin`.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, ClassVar

from snowflake.connector._internal.connection_config_mixin import (
    ConnectionConfigMixin,
    OptionsModifier,
)


__all__ = ["ConnectionConfig", "OptionsModifier"]


@dataclass
class ConnectionConfig(ConnectionConfigMixin):
    """Typed connection configuration derived from sf_core PARAM_DEFS.

    Fields use defaults from the Rust core where defined, ``None`` otherwise.
    Behavioural helpers (``from_kwargs``, ``to_options``, etc.) are inherited
    from :class:`ConnectionConfigMixin`.
    """

    # -- Connection parameters --------------------------------------------------
    account: str | None = None
    """Snowflake account identifier. Required"""

    allow_empty_proxy: bool | None = True
    """Empty PROXY value explicitly disables proxy (overrides env). Default: True"""

    application: str | None = None
    """User-facing application name sent as CLIENT_ENVIRONMENT.APPLICATION (falls back to client_app_id)"""

    authentication_timeout: int | None = 120
    """Timeout in seconds for native Okta SSO authentication. Default: 120"""

    authenticator: str | None = None
    """Authenticator type for the connection"""

    client_app_id: str | None = None
    """Driver identity sent as CLIENT_APP_ID in the login request (e.g. PythonConnector, SnowSQL)"""

    client_app_version: str | None = None
    """Driver version sent as CLIENT_APP_VERSION in the login request"""

    client_store_temporary_credential: bool | None = False
    """Enable MFA token caching for USERNAME_PASSWORD_MFA authentication. Default: False"""

    connect_timeout: int | None = None
    """TCP connect timeout in seconds for the HTTP client (0 or absent = system default)"""

    connection_diag_allowlist_path: str | None = None
    """Path to a pre-fetched allowlist.json; if absent the driver fetches it via system$allowlist()"""

    connection_diag_log_path: str | None = None
    """Directory where the diagnostic report file is written (defaults to system tmpdir)"""

    connection_name: str | None = None
    """Named connection to load from TOML configuration files"""

    crl_allow_certificates_without_crl_url: bool | None = False
    """Allow certificates that do not include a CRL distribution URL. Default: False"""

    crl_cache_dir: str | None = None
    """Directory for CRL cache files"""

    crl_check_mode: str | None = "DISABLED"
    """Certificate revocation check mode (DISABLED, ENABLED, ADVISORY). Default: 'DISABLED'"""

    crl_connection_timeout: int | None = 10
    """Connection timeout in seconds for CRL endpoints. Default: 10"""

    crl_enable_disk_caching: bool | None = True
    """Enable disk caching for CRL responses. Default: True"""

    crl_enable_memory_caching: bool | None = True
    """Enable in-memory caching for CRL responses. Default: True"""

    crl_http_timeout: int | None = 30
    """HTTP timeout in seconds for CRL endpoint requests. Default: 30"""

    crl_validity_time: int | None = 10
    """CRL cache validity time in days. Default: 10"""

    custom_root_store_path: str | None = None
    """Path to custom root certificate store"""

    disable_parallel_user_prompt: bool | None = True
    """When true (default), enables process-global serialization of interactive auth prompts (external browser, MFA,
    OAuth) so that only one prompt is shown per <user, host> when clientStoreTemporaryCredential is enabled. Set to
    false to allow each concurrent connection to show its own prompt..

    Default: True
    """

    disable_saml_url_check: bool | None = False
    """Skip the Okta SAML URL host-match safety check. Default: False"""

    enable_connection_diag: bool | None = False
    """Run connectivity diagnostics during connect and write a report. Default: False"""

    enable_server_session_keep_alive_auto_detection: bool | None = None
    """Enable auto-detection of async queries before logout (SNOW-2314152)"""

    host: str | None = None
    """Snowflake server hostname"""

    log_max_query_length: int | None = 80
    """Maximum number of characters of a query string to include in log messages. Default: 80"""

    log_query_parameters: bool | str | None = False
    """Include the (truncated) JSON bindings in INFO query logs (requires log_query_text). Default: False"""

    log_query_text: bool | str | None = False
    """Include the (truncated) SQL text in INFO query logs. Default: False"""

    logout_error_strategy: str | None = None
    """Error handling strategy for logout: 'best_effort' or 'strict'"""

    logout_max_attempts: int | None = None
    """Maximum total attempts for logout (1 = no retry, 3 = 2 retries)"""

    logout_request_timeout_seconds: int | None = None
    """Per-request socket timeout for individual logout attempts"""

    logout_total_timeout_seconds: int | None = None
    """Total timeout budget for logout operation including retries"""

    master_token: str | None = None
    """Pre-acquired master token for session token authentication"""

    master_validity_in_seconds: int | None = None
    """Remaining validity in seconds for the master token (session token auth)"""

    max_tls_version: str | None = "tls13"
    """Maximum TLS protocol version to negotiate (tls12 or tls13). Default: 'tls13'"""

    min_tls_version: str | None = "tls12"
    """Minimum TLS protocol version to negotiate (tls12 or tls13). Default: 'tls12'"""

    no_proxy: str | None = None
    """Comma-separated list of hosts to bypass the proxy for"""

    oauth_authorization_url: str | None = None
    """IdP authorization endpoint (defaults to https://{host}/oauth/authorize)"""

    oauth_client_id: str | None = None
    """OAuth client identifier (LOCAL_APPLICATION when Snowflake is the IdP)"""

    oauth_client_secret: str | None = None
    """OAuth client secret (redacted from logs)"""

    oauth_credentials_in_body: bool | None = False
    """Send client_id/client_secret in the OAUTH_CLIENT_CREDENTIALS token request body (client_secret_post) instead of
    the HTTP Basic header.

    Default: False
    """

    oauth_disable_console_login: bool | None = False
    """Disable EXTERNALBROWSER console-login (JDBC parity; does not gate OAuth). Default: False"""

    oauth_disable_pkce: bool | None = False
    """Disable PKCE S256 challenge for OAUTH_AUTHORIZATION_CODE (Python-compatible escape hatch). Default: False"""

    oauth_enable_dpop: bool | None = False
    """Enable RFC 9449 DPoP proof-of-possession (JDBC-compatible). Default: False"""

    oauth_enable_single_use_refresh_tokens: bool | None = False
    """Request single-use refresh-token rotation (Snowflake-IdP only). Default: False"""

    oauth_redirect_uri: str | None = None
    """Loopback redirect URI advertised to the IdP (defaults to http://127.0.0.1:<random>)"""

    oauth_scope: str | None = None
    """OAuth scope (space-separated; defaults to session:role:<role>)"""

    oauth_token_request_url: str | None = None
    """IdP token endpoint (CC only; defaults to https://{host}/oauth/token-request for AC).

    Required when authenticator=OAUTH_CLIENT_CREDENTIALS
    """

    okta_username: str | None = None
    """Okta username (defaults to the Snowflake user if omitted)"""

    passcode: str | None = None
    """MFA passcode for USERNAME_PASSWORD_MFA authentication"""

    passcode_in_password: bool | None = False
    """Whether the MFA passcode is appended to the password. Default: False"""

    password: str | None = None
    """Login password. Required when authenticator=SNOWFLAKE_PASSWORD"""

    port: int | None = None
    """Server port number"""

    preserve_underscores_in_hostname: bool | None = False
    """Preserve underscores in the hostname derived from the account name. Default: False"""

    private_key: Any | None = None
    """Private key for key-pair authentication (base64-encoded or PEM). Required when authenticator=SNOWFLAKE_JWT"""

    private_key_file: str | None = None
    """Path to private key file for key-pair authentication"""

    private_key_password: str | None = None
    """Passphrase for encrypted private key"""

    protocol: str | None = None
    """Connection protocol (http or https)"""

    proxy: str | None = None
    """Proxy URL ([scheme://][user:pass@]host[:port]); legacy ODBC `PROXY` form"""

    proxy_host: str | None = None
    """Proxy server hostname"""

    proxy_password: str | None = None
    """Proxy server password for Basic auth"""

    proxy_port: int | None = None
    """Proxy server port"""

    proxy_user: str | None = None
    """Proxy server username for Basic auth"""

    put_get_max_attempts: int | None = 6
    """Maximum total attempts for a single PUT/GET file transfer (1 = no retry). Default: 6"""

    retry_backoff_base_ms: int | None = 250
    """Initial exponential-backoff delay in milliseconds between retry attempts. Default: 250"""

    retry_backoff_cap_ms: int | None = 16000
    """Maximum exponential-backoff delay in milliseconds between retry attempts. Default: 16000"""

    retry_backoff_factor: float | None = 2
    """Multiplier applied to the backoff delay after each retry attempt. Default: 2"""

    retry_backoff_jitter: str | None = "decorrelated"
    """Backoff jitter strategy: 'none', 'full', or 'decorrelated'. Default: 'decorrelated'"""

    retry_extra_status_codes: str | None = None
    """Additional HTTP status codes (comma-separated) to retry on general HTTP and PUT/GET calls, beyond the built-in
    408/429/307/308/5xx set
    """

    retry_max_attempts: int | None = 6
    """Maximum total attempts for general HTTP calls (login, query, logout). 1 = no retry. Default: 6"""

    server_session_keep_alive: bool | None = None
    """Control server session lifecycle: true=keep alive, false=always logout, null=auto-detect"""

    server_url: str | None = None
    """Full server URL (alternative to host/port/protocol)"""

    session_token: str | None = None
    """Pre-acquired session token for session token authentication"""

    ssl: bool | None = None
    """Enable or disable SSL/TLS (sets protocol to https or http). Deprecated: use protocol instead"""

    tls_skip_verify: bool | None = False
    """Skip all TLS verification with a single switch: disables both certificate and hostname checks (and, since
    certificate verification is off, CRL revocation checks are bypassed too). Insecure; intended for testing only.

    Default: False
    """

    token: str | None = None
    """Pre-acquired bearer token (PAT or legacy OAUTH). Required when authenticator=PROGRAMMATIC_ACCESS_TOKEN"""

    unsafe_skip_config_file_permissions_check: bool | None = False
    """When true, skip file permission checks on config.toml and connections.toml during connection setup. Use in
    environments where permissions cannot be controlled (CI runners, containers). Unix-only; ignored on Windows.

    Default: False
    """

    use_proxy_env: bool | None = False
    """Honour HTTP_PROXY/HTTPS_PROXY/NO_PROXY env vars when no explicit proxy is set. Default: False"""

    user: str | None = None
    """Login username. Required"""

    validate_default_parameters: bool | None = False
    """Validate that the default database, schema, and warehouse exist on the server at connect time. Default: False"""

    verify_certificates: bool | None = True
    """Whether to verify TLS certificates. Default: True"""

    verify_hostname: bool | None = True
    """Whether to verify the server hostname in TLS. Default: True"""

    workload_identity_entra_resource: str | None = None
    """Azure Entra resource URI for managed-identity token (Azure only; defaults to
    api://fd3f753b-eed3-462c-b6a7-a4b5bb650aad)
    """

    workload_identity_impersonation_path: str | None = None
    """Comma-separated impersonation chain for WIF (AWS role ARNs or GCP service account emails)"""

    workload_identity_provider: str | None = None
    """Cloud provider for WIF attestation (AWS, AZURE, GCP, OIDC). Required when authenticator=WORKLOAD_IDENTITY"""

    # -- Session parameters --------------------------------------------------
    client_memory_limit: int | None = 1536
    """Memory budget in MB for chunk prefetch buffer (0 = unlimited). Default: 1536"""

    client_prefetch_threads: int | None = 4
    """Number of concurrent chunk prefetch threads for result set downloading. Default: 4"""

    client_session_keep_alive: bool | None = False
    """Keep the session alive with periodic heartbeat requests. Default: False"""

    client_session_keep_alive_heartbeat_frequency: int | None = None
    """Heartbeat frequency in seconds (clamped to interval master_token_validity/16..master_token_validity/4)"""

    database: str | None = None
    """Default database to use"""

    role: str | None = None
    """Default role to use"""

    schema: str | None = None
    """Default schema to use"""

    use_s3_regional_url: bool | None = False
    """Force the S3 regional endpoint for PUT/GET (PrivateLink-to-S3). Default: False"""

    warehouse: str | None = None
    """Default warehouse to use"""

    _ALIAS_MAP: ClassVar[dict[str, str]] = {
        "allowemptyproxy": "allow_empty_proxy",
        "allowunderscoresinhost": "preserve_underscores_in_hostname",
        "clientstoretemporarycredential": "client_store_temporary_credential",
        "crl_enabled": "crl_check_mode",
        "crl_mode": "crl_check_mode",
        "enable_stage_s3_privatelink_for_us_east_1": "use_s3_regional_url",
        "noproxy": "no_proxy",
        "oauth_token_url": "oauth_token_request_url",
        "oauthauthorizationurl": "oauth_authorization_url",
        "oauthclientid": "oauth_client_id",
        "oauthclientsecret": "oauth_client_secret",
        "oauthenablesingleuserefreshtokens": "oauth_enable_single_use_refresh_tokens",
        "oauthredirecturi": "oauth_redirect_uri",
        "oauthscope": "oauth_scope",
        "oauthtokenrequesturl": "oauth_token_request_url",
        "passcodeinpassword": "passcode_in_password",
        "priv_key_base64": "private_key",
        "priv_key_file": "private_key_file",
        "priv_key_file_pwd": "private_key_password",
        "priv_key_pwd": "private_key_password",
        "private_key_base64": "private_key",
        "private_key_file_pwd": "private_key_password",
        "private_key_pwd": "private_key_password",
        "proxywithenv": "use_proxy_env",
        "pwd": "password",
        "server": "host",
        "tls_custom_root_store_path": "custom_root_store_path",
        "tls_verify_certificates": "verify_certificates",
        "tls_verify_hostname": "verify_hostname",
        "uid": "user",
    }
    """Lowercased alias -> Python field name."""

    _PYTHON_TO_RUST_NAME: ClassVar[dict[str, str]] = {
        "client_memory_limit": "CLIENT_MEMORY_LIMIT",
        "client_prefetch_threads": "CLIENT_PREFETCH_THREADS",
        "client_session_keep_alive": "CLIENT_SESSION_KEEP_ALIVE",
        "client_session_keep_alive_heartbeat_frequency": "CLIENT_SESSION_KEEP_ALIVE_HEARTBEAT_FREQUENCY",
        "passcode_in_password": "passcodeInPassword",
    }
    """Python field name -> Rust canonical name (only for names that differ)."""

    _SENSITIVE_PARAMS: ClassVar[frozenset[str]] = frozenset(
        {
            "master_token",
            "oauth_client_secret",
            "passcode",
            "password",
            "private_key",
            "private_key_password",
            "proxy",
            "proxy_password",
            "session_token",
            "token",
        }
    )
    """Fields that contain secrets (for log redaction)."""
