"""Auto-generated from PARAM_DEFS in sf_core. DO NOT EDIT.

Regenerated by the generate-connection-config pre-commit hook whenever
param_registry.rs changes.  Any manual changes will be silently overwritten.
"""

from __future__ import annotations

import re

from collections.abc import Callable, Iterable
from dataclasses import dataclass, field
from typing import Any, ClassVar

from snowflake.connector._internal._private_key_helper import normalize_private_key
from snowflake.connector._internal.protobuf_gen.database_driver_v1_pb2 import ConfigSetting
from snowflake.connector.errors import ProgrammingError


OptionsModifier = Callable[[dict[str, Any]], dict[str, Any]]
"""Callable applied to the options dict produced by ``ConnectionConfig.to_options``.

A modifier may mutate the dict in place and/or return a new dict.  The return
value is fed into the next modifier in the chain.  See
``snowflake.connector._internal.logout_config_mapping.logout_config_options_modifier``
for an example modifier that re-applies legacy ``LogoutConfig`` semantics.
"""


@dataclass
class ConnectionConfig:
    """Typed connection configuration derived from sf_core PARAM_DEFS.

    Fields use defaults from the Rust core where defined, ``None`` otherwise.
    """

    # -- Connection parameters --------------------------------------------------
    account: str | None = None
    """Snowflake account identifier. Required"""

    authentication_timeout: int | None = 120
    """Timeout in seconds for native Okta SSO authentication. Default: 120"""

    authenticator: str | None = None
    """Authenticator type for the connection"""

    client_app_id: str | None = None
    """Application identifier sent by the client wrapper (e.g. PythonConnector)"""

    client_store_temporary_credential: bool | None = False
    """Enable MFA token caching for USERNAME_PASSWORD_MFA authentication. Default: False"""

    connection_name: str | None = None
    """Named connection to load from TOML configuration files"""

    crl_allow_certificates_without_crl_url: bool | None = False
    """Allow certificates that do not include a CRL distribution URL. Default: False"""

    crl_cache_dir: str | None = None
    """Directory for CRL cache files"""

    crl_check_mode: str | None = "DISABLED"
    """Certificate revocation check mode (DISABLED, ENABLED, ADVISORY). Default: 'DISABLED'"""

    crl_connection_timeout: int | None = 10
    """Connection timeout in seconds for CRL endpoints. Default: 10"""

    crl_enable_disk_caching: bool | None = True
    """Enable disk caching for CRL responses. Default: True"""

    crl_enable_memory_caching: bool | None = True
    """Enable in-memory caching for CRL responses. Default: True"""

    crl_http_timeout: int | None = 30
    """HTTP timeout in seconds for CRL endpoint requests. Default: 30"""

    crl_validity_time: int | None = 10
    """CRL cache validity time in days. Default: 10"""

    custom_root_store_path: str | None = None
    """Path to custom root certificate store"""

    disable_saml_url_check: bool | None = False
    """Skip the Okta SAML URL host-match safety check. Default: False"""

    enable_server_session_keep_alive_auto_detection: bool | None = None
    """Enable auto-detection of async queries before logout (SNOW-2314152)"""

    host: str | None = None
    """Snowflake server hostname"""

    log_max_query_length: int | None = 80
    """Maximum number of characters of a query string to include in log messages. Default: 80"""

    log_query_parameters: bool | str | None = False
    """Include the (truncated) JSON bindings in INFO query logs (requires log_query_text). Default: False"""

    log_query_text: bool | str | None = False
    """Include the (truncated) SQL text in INFO query logs. Default: False"""

    logout_error_strategy: str | None = None
    """Error handling strategy for logout: 'best_effort' or 'strict'"""

    logout_max_attempts: int | None = None
    """Maximum total attempts for logout (1 = no retry, 3 = 2 retries)"""

    logout_request_timeout_seconds: int | None = None
    """Per-request socket timeout for individual logout attempts"""

    logout_total_timeout_seconds: int | None = None
    """Total timeout budget for logout operation including retries"""

    okta_username: str | None = None
    """Okta username (defaults to the Snowflake user if omitted)"""

    passcode: str | None = None
    """MFA passcode for USERNAME_PASSWORD_MFA authentication"""

    passcode_in_password: bool | None = False
    """Whether the MFA passcode is appended to the password. Default: False"""

    password: str | None = None
    """Login password. Required when authenticator=SNOWFLAKE_PASSWORD"""

    port: int | None = None
    """Server port number"""

    preserve_underscores_in_hostname: bool | None = False
    """Preserve underscores in the hostname derived from the account name. Default: False"""

    private_key: Any | None = None
    """Private key for key-pair authentication (base64-encoded or PEM). Required when authenticator=SNOWFLAKE_JWT"""

    private_key_file: str | None = None
    """Path to private key file for key-pair authentication"""

    private_key_password: str | None = None
    """Passphrase for encrypted private key"""

    protocol: str | None = "https"
    """Connection protocol (http or https). Default: 'https'"""

    server_session_keep_alive: bool | None = None
    """Control server session lifecycle: true=keep alive, false=always logout, null=auto-detect"""

    server_url: str | None = None
    """Full server URL (alternative to host/port/protocol)"""

    token: str | None = None
    """Programmatic access token. Required when authenticator=PROGRAMMATIC_ACCESS_TOKEN"""

    user: str | None = None
    """Login username. Required"""

    verify_certificates: bool | None = True
    """Whether to verify TLS certificates. Default: True"""

    verify_hostname: bool | None = True
    """Whether to verify the server hostname in TLS. Default: True"""

    # -- Session parameters --------------------------------------------------
    client_prefetch_threads: int | None = 4
    """Number of concurrent chunk prefetch threads for result set downloading. Default: 4"""

    database: str | None = None
    """Default database to use"""

    role: str | None = None
    """Default role to use"""

    schema: str | None = None
    """Default schema to use"""

    warehouse: str | None = None
    """Default warehouse to use"""

    # -- Python-only parameters (not in PARAM_DEFS) --------------------
    session_parameters: dict[str, Any] | None = None
    """Session parameters to set at connection time."""

    application: str | None = None
    """Application name override."""

    numpy: bool | None = None
    """Use numpy for result set processing."""

    arrow_number_to_decimal: bool | None = None
    """Convert Arrow NUMBER columns to Python Decimal."""

    paramstyle: str | None = None
    """PEP 249 parameter binding style."""

    autocommit: bool | None = None
    """Enable/disable autocommit at connection time."""

    connections_file_path: str | None = None
    """Path to a TOML connections configuration file.

    Accepted by :class:`Connection` for forward-compatibility with
    snowflake-connector-python: callers can pass it today without breakage.
    Loading the file and merging the named ``connection_name`` profile into
    this config is **not yet wired up** in the universal driver; until that
    lands, the value is stored on the dataclass but does not influence
    connection behaviour.  TODO: integrate with ``ConfigManager``."""

    auto_cleanup: bool | None = None
    """Whether the connection should auto-close at interpreter shutdown via an
    ``atexit`` handler.  Python-only flag preserved for backward compatibility
    with snowflake-connector-python; never forwarded to the Rust core.  When
    ``None`` the wrapper treats it as ``True`` (legacy default)."""

    _extra: dict[str, Any] = field(default_factory=dict, repr=False)
    """Unknown kwargs forwarded to the Rust core for validation.

    Only values of the protobuf-supported scalar types (``bool``, ``int``,
    ``str``, ``float``, ``bytes``) survive the trip through
    :meth:`to_proto_options`; any other value type raises
    :class:`~snowflake.connector.errors.ProgrammingError` so misconfigurations
    fail loudly instead of being silently dropped.
    """

    _ALIAS_MAP: ClassVar[dict[str, str]] = {
        "allowunderscoresinhost": "preserve_underscores_in_hostname",
        "clientstoretemporarycredential": "client_store_temporary_credential",
        "crl_enabled": "crl_check_mode",
        "crl_mode": "crl_check_mode",
        "passcodeinpassword": "passcode_in_password",
        "priv_key_base64": "private_key",
        "priv_key_file": "private_key_file",
        "priv_key_file_pwd": "private_key_password",
        "priv_key_pwd": "private_key_password",
        "pwd": "password",
        "server": "host",
        "tls_custom_root_store_path": "custom_root_store_path",
        "tls_verify_certificates": "verify_certificates",
        "tls_verify_hostname": "verify_hostname",
        "uid": "user",
    }
    """Lowercased alias -> Python field name."""

    _PYTHON_TO_RUST_NAME: ClassVar[dict[str, str]] = {
        "client_prefetch_threads": "CLIENT_PREFETCH_THREADS",
        "passcode_in_password": "passcodeInPassword",
    }
    """Python field name -> Rust canonical name (only for names that differ)."""

    _SENSITIVE_PARAMS: ClassVar[frozenset[str]] = frozenset(
        {
            "passcode",
            "password",
            "private_key",
            "private_key_password",
            "token",
        }
    )
    """Fields that contain secrets (for log redaction)."""

    _PYTHON_ONLY: ClassVar[frozenset[str]] = frozenset(
        {
            "session_parameters",
            "application",
            "numpy",
            "arrow_number_to_decimal",
            "paramstyle",
            "autocommit",
            "connections_file_path",
            "auto_cleanup",
        }
    )
    """Fields handled only in Python, not forwarded to Rust."""

    _ALL_FIELDS: ClassVar[frozenset[str]] = frozenset(
        {
            "account",
            "application",
            "arrow_number_to_decimal",
            "authentication_timeout",
            "authenticator",
            "auto_cleanup",
            "autocommit",
            "client_app_id",
            "client_prefetch_threads",
            "client_store_temporary_credential",
            "connection_name",
            "connections_file_path",
            "crl_allow_certificates_without_crl_url",
            "crl_cache_dir",
            "crl_check_mode",
            "crl_connection_timeout",
            "crl_enable_disk_caching",
            "crl_enable_memory_caching",
            "crl_http_timeout",
            "crl_validity_time",
            "custom_root_store_path",
            "database",
            "disable_saml_url_check",
            "enable_server_session_keep_alive_auto_detection",
            "host",
            "log_max_query_length",
            "log_query_parameters",
            "log_query_text",
            "logout_error_strategy",
            "logout_max_attempts",
            "logout_request_timeout_seconds",
            "logout_total_timeout_seconds",
            "numpy",
            "okta_username",
            "paramstyle",
            "passcode",
            "passcode_in_password",
            "password",
            "port",
            "preserve_underscores_in_hostname",
            "private_key",
            "private_key_file",
            "private_key_password",
            "protocol",
            "role",
            "schema",
            "server_session_keep_alive",
            "server_url",
            "session_parameters",
            "token",
            "user",
            "verify_certificates",
            "verify_hostname",
            "warehouse",
        }
    )
    """All known field names (PARAM_DEF + Python-only)."""

    _LEGACY_REWRITES: ClassVar[dict[str, str]] = {
        "private_key_file_pwd": "private_key_password",
        "client_request_mfa_token": "client_store_temporary_credential",
    }
    """Legacy parameter names -> canonical replacements."""

    _APPLICATION_NAME: ClassVar[str] = "PythonConnector"
    """Default application name."""

    _APPLICATION_RE: ClassVar[re.Pattern[str]] = re.compile(r"^[\w\d_]+")
    """Regex for validating application names."""

    @classmethod
    def from_kwargs(cls, **kwargs: Any) -> ConnectionConfig:
        """Create a ConnectionConfig from keyword arguments.

        Resolves case-insensitive aliases, applies legacy parameter name
        rewrites, and collects unknown keys into ``_extra``.
        """
        # Apply legacy rewrites first
        for old_name, new_name in cls._LEGACY_REWRITES.items():
            if old_name in kwargs:
                value = kwargs.pop(old_name)
                if new_name not in kwargs:
                    kwargs[new_name] = value

        resolved: dict[str, Any] = {}
        extra: dict[str, Any] = {}

        for key, value in kwargs.items():
            lower_key = key.lower()
            # Direct field match (already snake_case)
            if lower_key in cls._ALL_FIELDS:
                resolved[lower_key] = value
            # Alias match
            elif lower_key in cls._ALIAS_MAP:
                field_name = cls._ALIAS_MAP[lower_key]
                resolved[field_name] = value
            else:
                extra[key] = value

        config = cls(**resolved)
        config._extra = extra
        return config

    @classmethod
    def from_connection_args(
        cls,
        connection_name: str | None = None,
        connections_file_path: str | None = None,
        config: ConnectionConfig | None = None,
        **kwargs: Any,
    ) -> ConnectionConfig:
        """Build a ConnectionConfig from Connection constructor arguments.

        Merges ``connection_name``, ``connections_file_path``, an optional
        pre-built ``config``, and any remaining ``**kwargs`` into a single
        :class:`ConnectionConfig`.  Raises ``ProgrammingError`` when both *config*
        and *kwargs* are supplied.

        Performs all value normalisation and validation so that the returned
        config is ready to be consumed by ``to_options()`` without further
        processing:

        * ``private_key`` – normalises RSAPrivateKey / bytes / str via
          :func:`normalize_private_key`.
        * ``application`` – validates against ``_APPLICATION_RE``, defaults to
          ``_APPLICATION_NAME``, and injects ``client_app_id`` into
          ``_extra`` for the Rust core.
        * ``autocommit`` – type-checked (must be ``bool``), then merged into
          ``session_parameters["AUTOCOMMIT"]``.
        """
        if config is not None and kwargs:
            raise ProgrammingError(
                "Cannot pass both a ConnectionConfig object and keyword arguments. Use one or the other."
            )

        if config is None:
            if connection_name is not None:
                kwargs["connection_name"] = connection_name
            if connections_file_path is not None:
                kwargs["connections_file_path"] = connections_file_path
            config = cls.from_kwargs(**kwargs)
        else:
            # config was provided — apply explicit overrides
            if connection_name is not None:
                config.connection_name = connection_name
            if connections_file_path is not None:
                config.connections_file_path = connections_file_path

        # -- private_key normalisation ------------------------------------
        if config.private_key is not None:
            config.private_key = normalize_private_key(config.private_key)

        # -- application validation & defaulting --------------------------
        application = config.application
        if application is None or (isinstance(application, str) and not application):
            config.application = cls._APPLICATION_NAME
        elif isinstance(application, str):
            if not cls._APPLICATION_RE.match(application):
                raise ProgrammingError(f"Invalid application name: {application!r}")
        else:
            raise ProgrammingError(f"Invalid application parameter (must be a non-empty string): {application!r}")
        # Inject client_app_id for the Rust core (always present in to_options via _extra)
        config._extra["client_app_id"] = config.application

        # -- autocommit validation & session_parameters injection ---------
        if config.autocommit is not None:
            if not isinstance(config.autocommit, bool):
                raise ProgrammingError(f"Invalid autocommit parameter: {config.autocommit!r}")
            if config.session_parameters is None:
                config.session_parameters = {}
            config.session_parameters["AUTOCOMMIT"] = str(config.autocommit).lower()

        return config

    def to_options(
        self,
        options_modifiers: Iterable[OptionsModifier] | None = None,
    ) -> dict[str, Any]:
        """Return non-None parameters for the Rust core.

        Excludes Python-only fields and maps Python field names back to
        Rust canonical names where they differ.  Includes ``_extra`` items.

        Args:
            options_modifiers: Optional iterable of callables applied to the
                options dict, in order, after it is built.  Each modifier
                receives the current dict and must return a dict (it may
                mutate the input in place).  The return value is passed to
                the next modifier.  Used to re-apply wrapper-specific
                legacy behaviour (e.g. ``LogoutConfig`` defaults & remap).
        """
        options: dict[str, Any] = {}

        for field_name in self._ALL_FIELDS:
            if field_name in self._PYTHON_ONLY:
                continue
            value = getattr(self, field_name, None)
            if value is None:
                continue
            # Map back to Rust canonical name if different
            rust_name = self._PYTHON_TO_RUST_NAME.get(field_name, field_name)
            options[rust_name] = value

        # Include unknown params for Rust-side validation
        options.update(self._extra)

        if options_modifiers:
            for modifier in options_modifiers:
                options = modifier(options)
        return options

    def redacted_options(
        self,
        options_modifiers: Iterable[OptionsModifier] | None = None,
    ) -> dict[str, Any]:
        """Like ``to_options()`` but with sensitive values replaced by ``'***'``."""
        return {k: ("***" if k in self._SENSITIVE_PARAMS else v) for k, v in self.to_options(options_modifiers).items()}

    def to_proto_options(
        self,
        options_modifiers: Iterable[OptionsModifier] | None = None,
    ) -> dict[str, ConfigSetting]:
        """Convert ``to_options()`` into protobuf ``ConfigSetting`` messages.

        Raises:
            ProgrammingError: if any option value is not one of the protobuf-
                supported scalar types (``bool``, ``int``, ``str``, ``float``,
                ``bytes``).  This commonly indicates that an unsupported value
                slipped into ``_extra`` (e.g. a list, dict, or custom object);
                surface it instead of silently dropping the entry.
        """
        proto: dict[str, ConfigSetting] = {}
        for key, value in self.to_options(options_modifiers).items():
            # Order matters: ``bool`` is a subclass of ``int`` in Python, so
            # the bool check has to come first to avoid coercing ``True`` /
            # ``False`` into ``int_value``.
            if isinstance(value, bool):
                proto[key] = ConfigSetting(bool_value=value)
            elif isinstance(value, int):
                proto[key] = ConfigSetting(int_value=value)
            elif isinstance(value, str):
                proto[key] = ConfigSetting(string_value=value)
            elif isinstance(value, float):
                proto[key] = ConfigSetting(double_value=value)
            elif isinstance(value, bytes):
                proto[key] = ConfigSetting(bytes_value=value)
            else:
                raise ProgrammingError(
                    f"Unsupported connection option type for {key!r}: "
                    f"{type(value).__name__}. Expected one of bool, int, "
                    f"str, float, or bytes."
                )
        return proto
