/**
 * AUTO-GENERATED - DO NOT EDIT.
 * Native binary types produced by "napi build"
 *
 * Generated by scripts/build-snowflake-sdk-core.mjs
 */
export declare class Column {
  getName(): string
  getIndex(): number
  getId(): number
  isNullable(): boolean
  getScale(): number | null
  getPrecision(): number | null
  getType(): string
  isString(): boolean
  isBinary(): boolean
  isNumber(): boolean
  isDecfloat(): boolean
  isBoolean(): boolean
  isDate(): boolean
  isTime(): boolean
  isTimestamp(): boolean
  isTimestampLtz(): boolean
  isTimestampNtz(): boolean
  isTimestampTz(): boolean
  isVariant(): boolean
  isObject(): boolean
  isArray(): boolean
  isMap(): boolean
}

export declare class Connection {
  constructor(options: Record<string, string>, sessionParameters: Record<string, string>)
  connect(): Promise<void>
  getSessionParameter(name: string): string | null
  execute(query: string): Statement
  getQueryResult(queryId: string): Statement
  destroy(): Promise<void>
}

export declare class Statement {
  waitForCompletion(): Promise<void>
  /**
   * Loads the next batch of rows. Returns `false` when the result set is
   * exhausted. Drain the loaded batch with
   * [`get_next_row`](Self::get_next_row) before calling this again.
   */
  fetchNextBatch(): Promise<boolean>
  /**
   * Returns the next row of the current batch, or `null` once that batch
   * is drained. Call [`fetch_next_batch`](Self::fetch_next_batch) to load
   * another.
   */
  getNextRow(): unknown[] | null
  getQueryId(): string | null
  getNumRows(): number | null
  getColumns(): Array<Column> | null
  getColumn(identifier: string | number): Column | null
  close(): void
  cancel(): Promise<void>
}
