/**
 * AUTO-GENERATED - DO NOT EDIT.
 * Native binary types produced by "napi build"
 *
 * Generated by scripts/build-snowflake-sdk-core.mjs
 */
export declare class Column {
  getName(): string
  getIndex(): number
  getId(): number
  isNullable(): boolean
  getScale(): number | null
  getPrecision(): number | null
  getType(): string
  isString(): boolean
  isBinary(): boolean
  isNumber(): boolean
  isDecfloat(): boolean
  isIntervalYearMonth(): boolean
  isIntervalDayTime(): boolean
  isBoolean(): boolean
  isDate(): boolean
  isTime(): boolean
  isTimestamp(): boolean
  isTimestampLtz(): boolean
  isTimestampNtz(): boolean
  isTimestampTz(): boolean
  isVariant(): boolean
  isObject(): boolean
  isArray(): boolean
  isMap(): boolean
  isVector(): boolean
}

export declare class Connection {
  constructor(options: Record<string, string>, sessionParameters: Record<string, string>, openExternalBrowserCallback?: ((arg: string) => void) | undefined | null)
  connect(): Promise<undefined>
  isUp(): boolean
  isValidAsync(): Promise<boolean>
  getSessionParameters(): KnownSessionParameters
  execute(query: string, bindings?: QueryBindings | undefined | null, parameters?: Record<string, string> | undefined | null): Statement
  getQueryStatus(queryId: string): Promise<QueryStatus>
  getQueryStatusThrowIfError(queryId: string): Promise<QueryStatus>
  getQueryResult(queryId: string): Statement
  destroy(): Promise<undefined>
}

export declare class Statement {
  waitForCompletion(): Promise<undefined>
  /**
   * Loads the next batch of rows. Returns `false` when the result set is
   * exhausted. Drain the loaded batch with
   * [`get_next_row`](Self::get_next_row) before calling this again.
   */
  fetchNextBatch(): Promise<boolean>
  /**
   * Returns the next row of the current batch, or `null` once that batch
   * is drained. Call [`fetch_next_batch`](Self::fetch_next_batch) to load
   * another.
   */
  getNextRow(): unknown[] | null
  getQueryId(): string | null
  getNumRows(): number | null
  /**
   * Not part of the driver's public API. Callers are suposed toinvoke this only after the
   * statement has finished, so a result that is not yet ready is a programming error
   */
  getSessionParametersSnapshot(): KnownSessionParameters
  getColumns(): Array<Column> | null
  getColumn(identifier: string | number): Column | null
  close(): void
  cancel(): Promise<void>
}

export declare function isAnError(status: QueryStatus): boolean

export declare function isStillRunning(status: QueryStatus): boolean

/**
 * Session parameters that both the Node.js layer and this bridge read for a
 * connection.
 *
 * Each field holds the value the server set for the session. When that value
 * is not available yet, the field falls back to a safe default instead of
 * failing.
 *
 * The value is not available in three cases:
 * - The connection was built from an existing session token and master token.
 *   Core then has no session parameters until the first query succeeds and the
 *   server returns them.
 * - The connection is not connected yet. Ideally we would never read session
 *   parameters before connecting, and the function that needs them would fail
 *   early instead. Building that guard is extra complexity we skip for now, so
 *   this case falls back to a default too.
 * - The connection is terminated, so there is nothing left to read.
 *   `Connection::get_session_parameters` answers with the defaults for any
 *   connection core reports as unusable, leaving the operation the caller is
 *   about to attempt to report the terminated connection itself.
 *
 * A read that fails while the connection is usable stays an error: a missing
 * key is expected, an unreadable map is not. `result_data_from` keeps that
 * strictness too — it snapshots these values to decode a result set that
 * already arrived, where a default would mean handing back rows formatted
 * against parameters the session never had.
 *
 * Ideally these defaults should not exist. Given the constraints above, we keep
 * them for now.
 */
export interface KnownSessionParameters {
  timeOutputFormat: string
  jsTreatIntegerAsBigInt: boolean
  clientStageArrayBindingThreshold: number
}

export declare enum QueryBindingFormat {
  Json = 0,
  Csv = 1
}

/**
 * Bind parameters handed down from the wrapper. `data` is either a JSON object
 * of `{ "1": { type, value }, ... }` or CSV text, selected by `format`.
 */
export interface QueryBindings {
  format: QueryBindingFormat
  data: string
}

export type QueryStatus =  'RUNNING'|
'ABORTING'|
'SUCCESS'|
'FAILED_WITH_ERROR'|
'ABORTED'|
'QUEUED'|
'FAILED_WITH_INCIDENT'|
'DISCONNECTED'|
'RESUMING_WAREHOUSE'|
'QUEUED_REPARING_WAREHOUSE'|
'RESTARTED'|
'BLOCKED'|
'NO_DATA';
