"""Shared SQL for SELECT 1M perf tests (e2e + recorded HTTP)."""

SQL_STRING = "SELECT L_COMMENT FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM LIMIT 1000000"
SQL_NUMBER = "SELECT L_LINENUMBER::INT FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM LIMIT 1000000"
SQL_DATE = "SELECT L_SHIPDATE FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM LIMIT 1000000"
SQL_FLOAT = "SELECT L_EXTENDEDPRICE FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM LIMIT 1000000"
SQL_DOUBLE = (
    "SELECT L_EXTENDEDPRICE::DOUBLE FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM LIMIT 1000000"
)
SQL_BOOLEAN = (
    "SELECT (L_TAX > 0.04)::BOOLEAN FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM LIMIT 1000000"
)
SQL_TIMESTAMP_NTZ = (
    "SELECT L_SHIPDATE::TIMESTAMP_NTZ FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM LIMIT 1000000"
)
SQL_TIMESTAMP_TZ = (
    "SELECT L_SHIPDATE::TIMESTAMP_TZ FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM LIMIT 1000000"
)
SQL_TIME = (
    "SELECT TIME_FROM_PARTS(MOD(L_ORDERKEY, 24), MOD(L_PARTKEY, 60), MOD(L_SUPPKEY, 60)) "
    "FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM LIMIT 1000000"
)
SQL_BINARY = (
    "SELECT TO_BINARY(L_COMMENT, 'UTF-8') FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM LIMIT 1000000"
)

SQL_15COLUMNS = """
            SELECT
                L_ORDERKEY,
                L_PARTKEY,
                L_SUPPKEY,
                L_LINENUMBER,
                L_QUANTITY,
                L_EXTENDEDPRICE,
                L_DISCOUNT,
                L_TAX,
                L_RETURNFLAG,
                L_LINESTATUS,
                L_SHIPDATE,
                L_COMMITDATE,
                L_RECEIPTDATE,
                L_SHIPINSTRUCT,
                L_COMMENT
            FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM
            LIMIT 1000000
        """

SQL_15COLUMNS_ORDERED = """
            SELECT
                L_ORDERKEY,
                L_PARTKEY,
                L_SUPPKEY,
                L_LINENUMBER,
                L_QUANTITY,
                L_EXTENDEDPRICE,
                L_DISCOUNT,
                L_TAX,
                L_RETURNFLAG,
                L_LINESTATUS,
                L_SHIPDATE,
                L_COMMITDATE,
                L_RECEIPTDATE,
                L_SHIPINSTRUCT,
                L_COMMENT
            FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM
            ORDER BY L_ORDERKEY
            LIMIT 1000000
        """

SQL_STRING_ORDERED = (
    "SELECT L_COMMENT FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM "
    "ORDER BY L_ORDERKEY LIMIT 1000000"
)
SQL_NUMBER_ORDERED = (
    "SELECT L_LINENUMBER::INT FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF100.LINEITEM "
    "ORDER BY L_ORDERKEY LIMIT 1000000"
)

# (type_key, sql) — used to register test_select_{type_key}_1M_arrow{,_default}
TYPE_QUERIES: list[tuple[str, str]] = [
    ("string", SQL_STRING),
    ("number", SQL_NUMBER),
    ("date", SQL_DATE),
    ("float", SQL_FLOAT),
    ("double", SQL_DOUBLE),
    ("boolean", SQL_BOOLEAN),
    ("timestamp_ntz", SQL_TIMESTAMP_NTZ),
    ("timestamp_tz", SQL_TIMESTAMP_TZ),
    ("time", SQL_TIME),
    ("binary", SQL_BINARY),
    ("15columns", SQL_15COLUMNS),
]

# Ordered variants stay CHAR-only (historical recorded_http baselines).
ORDERED_QUERIES: list[tuple[str, str]] = [
    ("string", SQL_STRING_ORDERED),
    ("number", SQL_NUMBER_ORDERED),
    ("15columns", SQL_15COLUMNS_ORDERED),
]
