package net.snowflake.client.internal.api.implementation.parameters;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

/** All Snowflake parameters the JDBC wrapper reads. Set and fetched through core. */
@Getter
@RequiredArgsConstructor
public enum Parameter implements Property {
  AUTOCOMMIT("AUTOCOMMIT", "true"),
  TIMEZONE("TIMEZONE", "America/Los_Angeles"),
  DATE_OUTPUT_FORMAT("DATE_OUTPUT_FORMAT", "YYYY-MM-DD"),
  TIME_OUTPUT_FORMAT("TIME_OUTPUT_FORMAT", "HH24:MI:SS"),
  TIMESTAMP_OUTPUT_FORMAT("TIMESTAMP_OUTPUT_FORMAT", "DY, DD MON YYYY HH24:MI:SS TZHTZM"),
  TIMESTAMP_NTZ_OUTPUT_FORMAT("TIMESTAMP_NTZ_OUTPUT_FORMAT", ""),
  TIMESTAMP_LTZ_OUTPUT_FORMAT("TIMESTAMP_LTZ_OUTPUT_FORMAT", ""),
  TIMESTAMP_TZ_OUTPUT_FORMAT("TIMESTAMP_TZ_OUTPUT_FORMAT", ""),
  JDBC_FORMAT_DATE_WITH_TIMEZONE("JDBC_FORMAT_DATE_WITH_TIMEZONE", "false"),
  JDBC_DEFAULT_FORMAT_DATE_WITH_TIMEZONE("JDBC_DEFAULT_FORMAT_DATE_WITH_TIMEZONE", "true"),
  JDBC_GET_DATE_USE_NULL_TIMEZONE("JDBC_GET_DATE_USE_NULL_TIMEZONE", "true"),
  JDBC_USE_SESSION_TIMEZONE("JDBC_USE_SESSION_TIMEZONE", "false"),
  JDBC_TREAT_TIMESTAMP_NTZ_AS_UTC("JDBC_TREAT_TIMESTAMP_NTZ_AS_UTC", "false"),
  JDBC_TREAT_DECIMAL_AS_INT("JDBC_TREAT_DECIMAL_AS_INT", "true"),
  CLIENT_TREAT_TIME_AS_WALL_CLOCK_TIME("CLIENT_TREAT_TIME_AS_WALL_CLOCK_TIME", "false"),
  CLIENT_HONOR_CLIENT_TZ_FOR_TIMESTAMP_NTZ("CLIENT_HONOR_CLIENT_TZ_FOR_TIMESTAMP_NTZ", "true"),
  CLIENT_TIMESTAMP_TYPE_MAPPING("CLIENT_TIMESTAMP_TYPE_MAPPING", "TIMESTAMP_LTZ"),
  CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX("CLIENT_METADATA_REQUEST_USE_CONNECTION_CTX", "false"),
  CLIENT_METADATA_USE_SESSION_DATABASE("CLIENT_METADATA_USE_SESSION_DATABASE", "false"),
  ENABLE_EXACT_SCHEMA_SEARCH_ENABLED("ENABLE_EXACT_SCHEMA_SEARCH_ENABLED", "false"),
  ENABLE_WILDCARDS_IN_SHOW_METADATA_COMMANDS("ENABLE_WILDCARDS_IN_SHOW_METADATA_COMMANDS", "true"),
  ENABLE_RETURN_TIMESTAMP_WITH_TIMEZONE("ENABLE_RETURN_TIMESTAMP_WITH_TIMEZONE", "true"),
  ENABLE_PATTERN_SEARCH("enablePatternSearch", "true"),
  STRINGS_QUOTED_FOR_COLUMN_DEF("STRINGS_QUOTED_FOR_COLUMN_DEF", "false"),
  VARCHAR_AND_BINARY_MAX_SIZE_IN_RESULT("VARCHAR_AND_BINARY_MAX_SIZE_IN_RESULT", "16777216"),
  LOG_QUERY_TEXT("log_query_text", "false"),
  TRACING("tracing", "");

  private final String key;
  private final String defaultVal;
}
