// <auto-generated>
//   This file was generated by proto_generator. Do not edit manually.
// </auto-generated>

namespace Snowflake.Data.Proto;

/// <summary>
/// Exception thrown when the core returns an application-level error.
/// </summary>
internal sealed class ServiceException : Exception
{
    /// <summary>
    /// The deserialized driver exception from the core.
    /// </summary>
    public DriverException Error { get; }

    public ServiceException(DriverException error)
        : base(error.ToString())
    {
        Error = error;
    }
}
