// <auto-generated>
//   This file was generated by proto_generator. Do not edit manually.
// </auto-generated>

namespace Snowflake.Data.Proto;

/// <summary>
/// Exception thrown when communication with the core fails at the transport level.
/// </summary>
internal sealed class TransportException : Exception
{
    public TransportException(string message)
        : base(message) { }

    public TransportException(string message, Exception innerException)
        : base(message, innerException) { }
}
