// <auto-generated>
//   This file was generated by proto_generator. Do not edit manually.
// </auto-generated>

namespace Snowflake.Data.Proto;

/// <summary>
/// Transport abstraction for communicating with sf_core via protobuf-over-FFI.
/// </summary>
internal interface ICoreTransport
{
    /// <summary>
    /// Send a synchronous message to the core and receive a response.
    /// </summary>
    TransportResponse HandleMessage(string service, string method, byte[] request);

    /// <summary>
    /// Send an asynchronous message to the core and receive a response.
    /// </summary>
    Task<TransportResponse> HandleMessageAsync(string service, string method, byte[] request, CancellationToken cancellationToken);
}
