pluginManagement {
    repositories {
        if (System.getenv('JENKINS_HOME')) {
            maven {
                name = 'Snowflake internal Artifactory (Maven Central proxy)'
                url 'https://artifactory.ci1.us-west-2.aws-dev.app.snowflake.com/artifactory/development-maven-virtual'
            }
        }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'jdbc'
