#!/bin/bash

set -e

# Generate Java code from thrift file
rm -rf jdbc/src/java/com/snowflake/jdbc/thrift_gen/
mkdir -p jdbc/src/java/com/snowflake/jdbc/thrift_gen/
thrift -r --gen java --out jdbc/src/java/com/snowflake/jdbc/thrift_gen/ thrift/database_driver_v1.thrift
for SOURCE in jdbc/src/java/com/snowflake/jdbc/thrift_gen/*.java; do
    TEMP_FILE=$(mktemp)
    echo "package com.snowflake.jdbc.thrift_gen;" > ${TEMP_FILE}
    # Remove date parameter from @javax.annotation.Generated annotation
    sed 's/@javax\.annotation\.Generated(value = "\([^"]*\)", date = "[^"]*")/@javax.annotation.Generated(value = "\1")/g' ${SOURCE} >> ${TEMP_FILE}
    cat ${TEMP_FILE} > ${SOURCE}
    rm ${TEMP_FILE}
done

# Generate Rust code from thrift file
rm -rf sf_core/src/thrift_gen/
mkdir -p sf_core/src/thrift_gen/
cat <<EOF > sf_core/src/thrift_gen/mod.rs
// This file is generated by scripts/generate_thrift.sh. Do not edit manually.
#![allow(unknown_lints)]
#![allow(clippy::all)]
#![allow(clippy::uninlined_format_args)]
pub mod database_driver_v1;
EOF
thrift -r --gen rs --out sf_core/src/thrift_gen/ thrift/database_driver_v1.thrift

# Generate Python code from thrift file
rm -rf pep249_dbapi/pep249_dbapi/thrift_gen/
mkdir -p pep249_dbapi/pep249_dbapi/thrift_gen/
thrift -r --gen py --out pep249_dbapi/pep249_dbapi/thrift_gen/ thrift/database_driver_v1.thrift

