package com.snowflake.jdbc.thrift_gen;
/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)")
public enum CertRevocationCheckMode implements org.apache.thrift.TEnum {
  DISABLED(0),
  ENABLED(1),
  ADVISORY(2);

  private final int value;

  private CertRevocationCheckMode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static CertRevocationCheckMode findByValue(int value) { 
    switch (value) {
      case 0:
        return DISABLED;
      case 1:
        return ENABLED;
      case 2:
        return ADVISORY;
      default:
        return null;
    }
  }
}
