package com.snowflake.jdbc.thrift_gen;
/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)")
public class DriverError extends org.apache.thrift.TUnion<DriverError, DriverError._Fields> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DriverError");
  private static final org.apache.thrift.protocol.TField AUTH_ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("authError", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField GENERIC_ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("genericError", org.apache.thrift.protocol.TType.STRUCT, (short)2);
  private static final org.apache.thrift.protocol.TField INTERNAL_ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("internalError", org.apache.thrift.protocol.TType.STRUCT, (short)3);
  private static final org.apache.thrift.protocol.TField MISSING_PARAMETER_FIELD_DESC = new org.apache.thrift.protocol.TField("missingParameter", org.apache.thrift.protocol.TType.STRUCT, (short)4);
  private static final org.apache.thrift.protocol.TField INVALID_PARAMETER_VALUE_FIELD_DESC = new org.apache.thrift.protocol.TField("invalidParameterValue", org.apache.thrift.protocol.TType.STRUCT, (short)5);
  private static final org.apache.thrift.protocol.TField LOGIN_ERROR_FIELD_DESC = new org.apache.thrift.protocol.TField("loginError", org.apache.thrift.protocol.TType.STRUCT, (short)6);

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    AUTH_ERROR((short)1, "authError"),
    GENERIC_ERROR((short)2, "genericError"),
    INTERNAL_ERROR((short)3, "internalError"),
    MISSING_PARAMETER((short)4, "missingParameter"),
    INVALID_PARAMETER_VALUE((short)5, "invalidParameterValue"),
    LOGIN_ERROR((short)6, "loginError");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // AUTH_ERROR
          return AUTH_ERROR;
        case 2: // GENERIC_ERROR
          return GENERIC_ERROR;
        case 3: // INTERNAL_ERROR
          return INTERNAL_ERROR;
        case 4: // MISSING_PARAMETER
          return MISSING_PARAMETER;
        case 5: // INVALID_PARAMETER_VALUE
          return INVALID_PARAMETER_VALUE;
        case 6: // LOGIN_ERROR
          return LOGIN_ERROR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.AUTH_ERROR, new org.apache.thrift.meta_data.FieldMetaData("authError", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, AuthenticationError.class)));
    tmpMap.put(_Fields.GENERIC_ERROR, new org.apache.thrift.meta_data.FieldMetaData("genericError", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, GenericError.class)));
    tmpMap.put(_Fields.INTERNAL_ERROR, new org.apache.thrift.meta_data.FieldMetaData("internalError", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, InternalError.class)));
    tmpMap.put(_Fields.MISSING_PARAMETER, new org.apache.thrift.meta_data.FieldMetaData("missingParameter", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, MissingParameter.class)));
    tmpMap.put(_Fields.INVALID_PARAMETER_VALUE, new org.apache.thrift.meta_data.FieldMetaData("invalidParameterValue", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, InvalidParameterValue.class)));
    tmpMap.put(_Fields.LOGIN_ERROR, new org.apache.thrift.meta_data.FieldMetaData("loginError", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, LoginError.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DriverError.class, metaDataMap);
  }

  public DriverError() {
    super();
  }

  public DriverError(_Fields setField, java.lang.Object value) {
    super(setField, value);
  }

  public DriverError(DriverError other) {
    super(other);
  }
  @Override
  public DriverError deepCopy() {
    return new DriverError(this);
  }

  public static DriverError authError(AuthenticationError value) {
    DriverError x = new DriverError();
    x.setAuthError(value);
    return x;
  }

  public static DriverError genericError(GenericError value) {
    DriverError x = new DriverError();
    x.setGenericError(value);
    return x;
  }

  public static DriverError internalError(InternalError value) {
    DriverError x = new DriverError();
    x.setInternalError(value);
    return x;
  }

  public static DriverError missingParameter(MissingParameter value) {
    DriverError x = new DriverError();
    x.setMissingParameter(value);
    return x;
  }

  public static DriverError invalidParameterValue(InvalidParameterValue value) {
    DriverError x = new DriverError();
    x.setInvalidParameterValue(value);
    return x;
  }

  public static DriverError loginError(LoginError value) {
    DriverError x = new DriverError();
    x.setLoginError(value);
    return x;
  }


  @Override
  protected void checkType(_Fields setField, java.lang.Object value) throws java.lang.ClassCastException {
    switch (setField) {
      case AUTH_ERROR:
        if (value instanceof AuthenticationError) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type AuthenticationError for field 'authError', but got " + value.getClass().getSimpleName());
      case GENERIC_ERROR:
        if (value instanceof GenericError) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type GenericError for field 'genericError', but got " + value.getClass().getSimpleName());
      case INTERNAL_ERROR:
        if (value instanceof InternalError) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type InternalError for field 'internalError', but got " + value.getClass().getSimpleName());
      case MISSING_PARAMETER:
        if (value instanceof MissingParameter) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type MissingParameter for field 'missingParameter', but got " + value.getClass().getSimpleName());
      case INVALID_PARAMETER_VALUE:
        if (value instanceof InvalidParameterValue) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type InvalidParameterValue for field 'invalidParameterValue', but got " + value.getClass().getSimpleName());
      case LOGIN_ERROR:
        if (value instanceof LoginError) {
          break;
        }
        throw new java.lang.ClassCastException("Was expecting value of type LoginError for field 'loginError', but got " + value.getClass().getSimpleName());
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected java.lang.Object standardSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, org.apache.thrift.protocol.TField field) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(field.id);
    if (setField != null) {
      switch (setField) {
        case AUTH_ERROR:
          if (field.type == AUTH_ERROR_FIELD_DESC.type) {
            AuthenticationError authError;
            authError = new AuthenticationError();
            authError.read(iprot);
            return authError;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case GENERIC_ERROR:
          if (field.type == GENERIC_ERROR_FIELD_DESC.type) {
            GenericError genericError;
            genericError = new GenericError();
            genericError.read(iprot);
            return genericError;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case INTERNAL_ERROR:
          if (field.type == INTERNAL_ERROR_FIELD_DESC.type) {
            InternalError internalError;
            internalError = new InternalError();
            internalError.read(iprot);
            return internalError;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case MISSING_PARAMETER:
          if (field.type == MISSING_PARAMETER_FIELD_DESC.type) {
            MissingParameter missingParameter;
            missingParameter = new MissingParameter();
            missingParameter.read(iprot);
            return missingParameter;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case INVALID_PARAMETER_VALUE:
          if (field.type == INVALID_PARAMETER_VALUE_FIELD_DESC.type) {
            InvalidParameterValue invalidParameterValue;
            invalidParameterValue = new InvalidParameterValue();
            invalidParameterValue.read(iprot);
            return invalidParameterValue;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        case LOGIN_ERROR:
          if (field.type == LOGIN_ERROR_FIELD_DESC.type) {
            LoginError loginError;
            loginError = new LoginError();
            loginError.read(iprot);
            return loginError;
          } else {
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
            return null;
          }
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      org.apache.thrift.protocol.TProtocolUtil.skip(iprot, field.type);
      return null;
    }
  }

  @Override
  protected void standardSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case AUTH_ERROR:
        AuthenticationError authError = (AuthenticationError)value_;
        authError.write(oprot);
        return;
      case GENERIC_ERROR:
        GenericError genericError = (GenericError)value_;
        genericError.write(oprot);
        return;
      case INTERNAL_ERROR:
        InternalError internalError = (InternalError)value_;
        internalError.write(oprot);
        return;
      case MISSING_PARAMETER:
        MissingParameter missingParameter = (MissingParameter)value_;
        missingParameter.write(oprot);
        return;
      case INVALID_PARAMETER_VALUE:
        InvalidParameterValue invalidParameterValue = (InvalidParameterValue)value_;
        invalidParameterValue.write(oprot);
        return;
      case LOGIN_ERROR:
        LoginError loginError = (LoginError)value_;
        loginError.write(oprot);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected java.lang.Object tupleSchemeReadValue(org.apache.thrift.protocol.TProtocol iprot, short fieldID) throws org.apache.thrift.TException {
    _Fields setField = _Fields.findByThriftId(fieldID);
    if (setField != null) {
      switch (setField) {
        case AUTH_ERROR:
          AuthenticationError authError;
          authError = new AuthenticationError();
          authError.read(iprot);
          return authError;
        case GENERIC_ERROR:
          GenericError genericError;
          genericError = new GenericError();
          genericError.read(iprot);
          return genericError;
        case INTERNAL_ERROR:
          InternalError internalError;
          internalError = new InternalError();
          internalError.read(iprot);
          return internalError;
        case MISSING_PARAMETER:
          MissingParameter missingParameter;
          missingParameter = new MissingParameter();
          missingParameter.read(iprot);
          return missingParameter;
        case INVALID_PARAMETER_VALUE:
          InvalidParameterValue invalidParameterValue;
          invalidParameterValue = new InvalidParameterValue();
          invalidParameterValue.read(iprot);
          return invalidParameterValue;
        case LOGIN_ERROR:
          LoginError loginError;
          loginError = new LoginError();
          loginError.read(iprot);
          return loginError;
        default:
          throw new java.lang.IllegalStateException("setField wasn't null, but didn't match any of the case statements!");
      }
    } else {
      throw new org.apache.thrift.protocol.TProtocolException("Couldn't find a field with field id " + fieldID);
    }
  }

  @Override
  protected void tupleSchemeWriteValue(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    switch (setField_) {
      case AUTH_ERROR:
        AuthenticationError authError = (AuthenticationError)value_;
        authError.write(oprot);
        return;
      case GENERIC_ERROR:
        GenericError genericError = (GenericError)value_;
        genericError.write(oprot);
        return;
      case INTERNAL_ERROR:
        InternalError internalError = (InternalError)value_;
        internalError.write(oprot);
        return;
      case MISSING_PARAMETER:
        MissingParameter missingParameter = (MissingParameter)value_;
        missingParameter.write(oprot);
        return;
      case INVALID_PARAMETER_VALUE:
        InvalidParameterValue invalidParameterValue = (InvalidParameterValue)value_;
        invalidParameterValue.write(oprot);
        return;
      case LOGIN_ERROR:
        LoginError loginError = (LoginError)value_;
        loginError.write(oprot);
        return;
      default:
        throw new java.lang.IllegalStateException("Cannot write union with unknown field " + setField_);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TField getFieldDesc(_Fields setField) {
    switch (setField) {
      case AUTH_ERROR:
        return AUTH_ERROR_FIELD_DESC;
      case GENERIC_ERROR:
        return GENERIC_ERROR_FIELD_DESC;
      case INTERNAL_ERROR:
        return INTERNAL_ERROR_FIELD_DESC;
      case MISSING_PARAMETER:
        return MISSING_PARAMETER_FIELD_DESC;
      case INVALID_PARAMETER_VALUE:
        return INVALID_PARAMETER_VALUE_FIELD_DESC;
      case LOGIN_ERROR:
        return LOGIN_ERROR_FIELD_DESC;
      default:
        throw new java.lang.IllegalArgumentException("Unknown field id " + setField);
    }
  }

  @Override
  protected org.apache.thrift.protocol.TStruct getStructDesc() {
    return STRUCT_DESC;
  }

  @Override
  protected _Fields enumForId(short id) {
    return _Fields.findByThriftIdOrThrow(id);
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }


  public AuthenticationError getAuthError() {
    if (getSetField() == _Fields.AUTH_ERROR) {
      return (AuthenticationError)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'authError' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setAuthError(AuthenticationError value) {
    setField_ = _Fields.AUTH_ERROR;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.AUTH_ERROR");
  }

  public GenericError getGenericError() {
    if (getSetField() == _Fields.GENERIC_ERROR) {
      return (GenericError)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'genericError' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setGenericError(GenericError value) {
    setField_ = _Fields.GENERIC_ERROR;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.GENERIC_ERROR");
  }

  public InternalError getInternalError() {
    if (getSetField() == _Fields.INTERNAL_ERROR) {
      return (InternalError)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'internalError' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setInternalError(InternalError value) {
    setField_ = _Fields.INTERNAL_ERROR;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.INTERNAL_ERROR");
  }

  public MissingParameter getMissingParameter() {
    if (getSetField() == _Fields.MISSING_PARAMETER) {
      return (MissingParameter)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'missingParameter' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setMissingParameter(MissingParameter value) {
    setField_ = _Fields.MISSING_PARAMETER;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.MISSING_PARAMETER");
  }

  public InvalidParameterValue getInvalidParameterValue() {
    if (getSetField() == _Fields.INVALID_PARAMETER_VALUE) {
      return (InvalidParameterValue)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'invalidParameterValue' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setInvalidParameterValue(InvalidParameterValue value) {
    setField_ = _Fields.INVALID_PARAMETER_VALUE;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.INVALID_PARAMETER_VALUE");
  }

  public LoginError getLoginError() {
    if (getSetField() == _Fields.LOGIN_ERROR) {
      return (LoginError)getFieldValue();
    } else {
      throw new java.lang.RuntimeException("Cannot get field 'loginError' because union is currently set to " + getFieldDesc(getSetField()).name);
    }
  }

  public void setLoginError(LoginError value) {
    setField_ = _Fields.LOGIN_ERROR;
    value_ = java.util.Objects.requireNonNull(value,"_Fields.LOGIN_ERROR");
  }

  public boolean isSetAuthError() {
    return setField_ == _Fields.AUTH_ERROR;
  }


  public boolean isSetGenericError() {
    return setField_ == _Fields.GENERIC_ERROR;
  }


  public boolean isSetInternalError() {
    return setField_ == _Fields.INTERNAL_ERROR;
  }


  public boolean isSetMissingParameter() {
    return setField_ == _Fields.MISSING_PARAMETER;
  }


  public boolean isSetInvalidParameterValue() {
    return setField_ == _Fields.INVALID_PARAMETER_VALUE;
  }


  public boolean isSetLoginError() {
    return setField_ == _Fields.LOGIN_ERROR;
  }


  public boolean equals(java.lang.Object other) {
    if (other instanceof DriverError) {
      return equals((DriverError)other);
    } else {
      return false;
    }
  }

  public boolean equals(DriverError other) {
    return other != null && getSetField() == other.getSetField() && getFieldValue().equals(other.getFieldValue());
  }

  @Override
  public int compareTo(DriverError other) {
    int lastComparison = org.apache.thrift.TBaseHelper.compareTo(getSetField(), other.getSetField());
    if (lastComparison == 0) {
      return org.apache.thrift.TBaseHelper.compareTo(getFieldValue(), other.getFieldValue());
    }
    return lastComparison;
  }


  @Override
  public int hashCode() {
    java.util.List<java.lang.Object> list = new java.util.ArrayList<java.lang.Object>();
    list.add(this.getClass().getName());
    org.apache.thrift.TFieldIdEnum setField = getSetField();
    if (setField != null) {
      list.add(setField.getThriftFieldId());
      java.lang.Object value = getFieldValue();
      if (value instanceof org.apache.thrift.TEnum) {
        list.add(((org.apache.thrift.TEnum)getFieldValue()).getValue());
      } else {
        list.add(value);
      }
    }
    return list.hashCode();
  }
  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }


}
