package com.snowflake.jdbc.thrift_gen;
/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)")
public class DriverException extends org.apache.thrift.TException implements org.apache.thrift.TBase<DriverException, DriverException._Fields>, java.io.Serializable, Cloneable, Comparable<DriverException> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("DriverException");

  private static final org.apache.thrift.protocol.TField MESSAGE_FIELD_DESC = new org.apache.thrift.protocol.TField("message", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField STATUS_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("status_code", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField VENDOR_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("vendor_code", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField SQLSTATE_FIELD_DESC = new org.apache.thrift.protocol.TField("sqlstate", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField DETAILS_FIELD_DESC = new org.apache.thrift.protocol.TField("details", org.apache.thrift.protocol.TType.LIST, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new DriverExceptionStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new DriverExceptionTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String message; // required
  /**
   * 
   * @see StatusCode
   */
  public @org.apache.thrift.annotation.Nullable StatusCode status_code; // required
  public int vendor_code; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String sqlstate; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<ErrorDetail> details; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    MESSAGE((short)1, "message"),
    /**
     * 
     * @see StatusCode
     */
    STATUS_CODE((short)2, "status_code"),
    VENDOR_CODE((short)3, "vendor_code"),
    SQLSTATE((short)4, "sqlstate"),
    DETAILS((short)5, "details");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // MESSAGE
          return MESSAGE;
        case 2: // STATUS_CODE
          return STATUS_CODE;
        case 3: // VENDOR_CODE
          return VENDOR_CODE;
        case 4: // SQLSTATE
          return SQLSTATE;
        case 5: // DETAILS
          return DETAILS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VENDOR_CODE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.VENDOR_CODE,_Fields.SQLSTATE,_Fields.DETAILS};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.MESSAGE, new org.apache.thrift.meta_data.FieldMetaData("message", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.STATUS_CODE, new org.apache.thrift.meta_data.FieldMetaData("status_code", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, StatusCode.class)));
    tmpMap.put(_Fields.VENDOR_CODE, new org.apache.thrift.meta_data.FieldMetaData("vendor_code", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.SQLSTATE, new org.apache.thrift.meta_data.FieldMetaData("sqlstate", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DETAILS, new org.apache.thrift.meta_data.FieldMetaData("details", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ErrorDetail.class))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(DriverException.class, metaDataMap);
  }

  public DriverException() {
  }

  public DriverException(
    java.lang.String message,
    StatusCode status_code)
  {
    this();
    this.message = message;
    this.status_code = status_code;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public DriverException(DriverException other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetMessage()) {
      this.message = other.message;
    }
    if (other.isSetStatus_code()) {
      this.status_code = other.status_code;
    }
    this.vendor_code = other.vendor_code;
    if (other.isSetSqlstate()) {
      this.sqlstate = other.sqlstate;
    }
    if (other.isSetDetails()) {
      java.util.List<ErrorDetail> __this__details = new java.util.ArrayList<ErrorDetail>(other.details.size());
      for (ErrorDetail other_element : other.details) {
        __this__details.add(new ErrorDetail(other_element));
      }
      this.details = __this__details;
    }
  }

  @Override
  public DriverException deepCopy() {
    return new DriverException(this);
  }

  @Override
  public void clear() {
    this.message = null;
    this.status_code = null;
    setVendor_codeIsSet(false);
    this.vendor_code = 0;
    this.sqlstate = null;
    this.details = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getMessage() {
    return this.message;
  }

  public DriverException setMessage(@org.apache.thrift.annotation.Nullable java.lang.String message) {
    this.message = message;
    return this;
  }

  public void unsetMessage() {
    this.message = null;
  }

  /** Returns true if field message is set (has been assigned a value) and false otherwise */
  public boolean isSetMessage() {
    return this.message != null;
  }

  public void setMessageIsSet(boolean value) {
    if (!value) {
      this.message = null;
    }
  }

  /**
   * 
   * @see StatusCode
   */
  @org.apache.thrift.annotation.Nullable
  public StatusCode getStatus_code() {
    return this.status_code;
  }

  /**
   * 
   * @see StatusCode
   */
  public DriverException setStatus_code(@org.apache.thrift.annotation.Nullable StatusCode status_code) {
    this.status_code = status_code;
    return this;
  }

  public void unsetStatus_code() {
    this.status_code = null;
  }

  /** Returns true if field status_code is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus_code() {
    return this.status_code != null;
  }

  public void setStatus_codeIsSet(boolean value) {
    if (!value) {
      this.status_code = null;
    }
  }

  public int getVendor_code() {
    return this.vendor_code;
  }

  public DriverException setVendor_code(int vendor_code) {
    this.vendor_code = vendor_code;
    setVendor_codeIsSet(true);
    return this;
  }

  public void unsetVendor_code() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VENDOR_CODE_ISSET_ID);
  }

  /** Returns true if field vendor_code is set (has been assigned a value) and false otherwise */
  public boolean isSetVendor_code() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VENDOR_CODE_ISSET_ID);
  }

  public void setVendor_codeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VENDOR_CODE_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getSqlstate() {
    return this.sqlstate;
  }

  public DriverException setSqlstate(@org.apache.thrift.annotation.Nullable java.lang.String sqlstate) {
    this.sqlstate = sqlstate;
    return this;
  }

  public void unsetSqlstate() {
    this.sqlstate = null;
  }

  /** Returns true if field sqlstate is set (has been assigned a value) and false otherwise */
  public boolean isSetSqlstate() {
    return this.sqlstate != null;
  }

  public void setSqlstateIsSet(boolean value) {
    if (!value) {
      this.sqlstate = null;
    }
  }

  public int getDetailsSize() {
    return (this.details == null) ? 0 : this.details.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<ErrorDetail> getDetailsIterator() {
    return (this.details == null) ? null : this.details.iterator();
  }

  public void addToDetails(ErrorDetail elem) {
    if (this.details == null) {
      this.details = new java.util.ArrayList<ErrorDetail>();
    }
    this.details.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<ErrorDetail> getDetails() {
    return this.details;
  }

  public DriverException setDetails(@org.apache.thrift.annotation.Nullable java.util.List<ErrorDetail> details) {
    this.details = details;
    return this;
  }

  public void unsetDetails() {
    this.details = null;
  }

  /** Returns true if field details is set (has been assigned a value) and false otherwise */
  public boolean isSetDetails() {
    return this.details != null;
  }

  public void setDetailsIsSet(boolean value) {
    if (!value) {
      this.details = null;
    }
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case MESSAGE:
      if (value == null) {
        unsetMessage();
      } else {
        setMessage((java.lang.String)value);
      }
      break;

    case STATUS_CODE:
      if (value == null) {
        unsetStatus_code();
      } else {
        setStatus_code((StatusCode)value);
      }
      break;

    case VENDOR_CODE:
      if (value == null) {
        unsetVendor_code();
      } else {
        setVendor_code((java.lang.Integer)value);
      }
      break;

    case SQLSTATE:
      if (value == null) {
        unsetSqlstate();
      } else {
        setSqlstate((java.lang.String)value);
      }
      break;

    case DETAILS:
      if (value == null) {
        unsetDetails();
      } else {
        setDetails((java.util.List<ErrorDetail>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case MESSAGE:
      return getMessage();

    case STATUS_CODE:
      return getStatus_code();

    case VENDOR_CODE:
      return getVendor_code();

    case SQLSTATE:
      return getSqlstate();

    case DETAILS:
      return getDetails();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case MESSAGE:
      return isSetMessage();
    case STATUS_CODE:
      return isSetStatus_code();
    case VENDOR_CODE:
      return isSetVendor_code();
    case SQLSTATE:
      return isSetSqlstate();
    case DETAILS:
      return isSetDetails();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof DriverException)
      return this.equals((DriverException)that);
    return false;
  }

  public boolean equals(DriverException that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_message = true && this.isSetMessage();
    boolean that_present_message = true && that.isSetMessage();
    if (this_present_message || that_present_message) {
      if (!(this_present_message && that_present_message))
        return false;
      if (!this.message.equals(that.message))
        return false;
    }

    boolean this_present_status_code = true && this.isSetStatus_code();
    boolean that_present_status_code = true && that.isSetStatus_code();
    if (this_present_status_code || that_present_status_code) {
      if (!(this_present_status_code && that_present_status_code))
        return false;
      if (!this.status_code.equals(that.status_code))
        return false;
    }

    boolean this_present_vendor_code = true && this.isSetVendor_code();
    boolean that_present_vendor_code = true && that.isSetVendor_code();
    if (this_present_vendor_code || that_present_vendor_code) {
      if (!(this_present_vendor_code && that_present_vendor_code))
        return false;
      if (this.vendor_code != that.vendor_code)
        return false;
    }

    boolean this_present_sqlstate = true && this.isSetSqlstate();
    boolean that_present_sqlstate = true && that.isSetSqlstate();
    if (this_present_sqlstate || that_present_sqlstate) {
      if (!(this_present_sqlstate && that_present_sqlstate))
        return false;
      if (!this.sqlstate.equals(that.sqlstate))
        return false;
    }

    boolean this_present_details = true && this.isSetDetails();
    boolean that_present_details = true && that.isSetDetails();
    if (this_present_details || that_present_details) {
      if (!(this_present_details && that_present_details))
        return false;
      if (!this.details.equals(that.details))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetMessage()) ? 131071 : 524287);
    if (isSetMessage())
      hashCode = hashCode * 8191 + message.hashCode();

    hashCode = hashCode * 8191 + ((isSetStatus_code()) ? 131071 : 524287);
    if (isSetStatus_code())
      hashCode = hashCode * 8191 + status_code.getValue();

    hashCode = hashCode * 8191 + ((isSetVendor_code()) ? 131071 : 524287);
    if (isSetVendor_code())
      hashCode = hashCode * 8191 + vendor_code;

    hashCode = hashCode * 8191 + ((isSetSqlstate()) ? 131071 : 524287);
    if (isSetSqlstate())
      hashCode = hashCode * 8191 + sqlstate.hashCode();

    hashCode = hashCode * 8191 + ((isSetDetails()) ? 131071 : 524287);
    if (isSetDetails())
      hashCode = hashCode * 8191 + details.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(DriverException other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetMessage(), other.isSetMessage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMessage()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.message, other.message);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetStatus_code(), other.isSetStatus_code());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus_code()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status_code, other.status_code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetVendor_code(), other.isSetVendor_code());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVendor_code()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.vendor_code, other.vendor_code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSqlstate(), other.isSetSqlstate());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSqlstate()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sqlstate, other.sqlstate);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDetails(), other.isSetDetails());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDetails()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.details, other.details);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("DriverException(");
    boolean first = true;

    sb.append("message:");
    if (this.message == null) {
      sb.append("null");
    } else {
      sb.append(this.message);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("status_code:");
    if (this.status_code == null) {
      sb.append("null");
    } else {
      sb.append(this.status_code);
    }
    first = false;
    if (isSetVendor_code()) {
      if (!first) sb.append(", ");
      sb.append("vendor_code:");
      sb.append(this.vendor_code);
      first = false;
    }
    if (isSetSqlstate()) {
      if (!first) sb.append(", ");
      sb.append("sqlstate:");
      if (this.sqlstate == null) {
        sb.append("null");
      } else {
        sb.append(this.sqlstate);
      }
      first = false;
    }
    if (isSetDetails()) {
      if (!first) sb.append(", ");
      sb.append("details:");
      if (this.details == null) {
        sb.append("null");
      } else {
        sb.append(this.details);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (message == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'message' was not present! Struct: " + toString());
    }
    if (status_code == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'status_code' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class DriverExceptionStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DriverExceptionStandardScheme getScheme() {
      return new DriverExceptionStandardScheme();
    }
  }

  private static class DriverExceptionStandardScheme extends org.apache.thrift.scheme.StandardScheme<DriverException> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, DriverException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // MESSAGE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.message = iprot.readString();
              struct.setMessageIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // STATUS_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.status_code = StatusCode.findByValue(iprot.readI32());
              struct.setStatus_codeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // VENDOR_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.vendor_code = iprot.readI32();
              struct.setVendor_codeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SQLSTATE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sqlstate = iprot.readString();
              struct.setSqlstateIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // DETAILS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.details = new java.util.ArrayList<ErrorDetail>(_list0.size);
                @org.apache.thrift.annotation.Nullable ErrorDetail _elem1;
                for (int _i2 = 0; _i2 < _list0.size; ++_i2)
                {
                  _elem1 = new ErrorDetail();
                  _elem1.read(iprot);
                  struct.details.add(_elem1);
                }
                iprot.readListEnd();
              }
              struct.setDetailsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, DriverException struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.message != null) {
        oprot.writeFieldBegin(MESSAGE_FIELD_DESC);
        oprot.writeString(struct.message);
        oprot.writeFieldEnd();
      }
      if (struct.status_code != null) {
        oprot.writeFieldBegin(STATUS_CODE_FIELD_DESC);
        oprot.writeI32(struct.status_code.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.isSetVendor_code()) {
        oprot.writeFieldBegin(VENDOR_CODE_FIELD_DESC);
        oprot.writeI32(struct.vendor_code);
        oprot.writeFieldEnd();
      }
      if (struct.sqlstate != null) {
        if (struct.isSetSqlstate()) {
          oprot.writeFieldBegin(SQLSTATE_FIELD_DESC);
          oprot.writeString(struct.sqlstate);
          oprot.writeFieldEnd();
        }
      }
      if (struct.details != null) {
        if (struct.isSetDetails()) {
          oprot.writeFieldBegin(DETAILS_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.details.size()));
            for (ErrorDetail _iter3 : struct.details)
            {
              _iter3.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class DriverExceptionTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public DriverExceptionTupleScheme getScheme() {
      return new DriverExceptionTupleScheme();
    }
  }

  private static class DriverExceptionTupleScheme extends org.apache.thrift.scheme.TupleScheme<DriverException> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, DriverException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.message);
      oprot.writeI32(struct.status_code.getValue());
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetVendor_code()) {
        optionals.set(0);
      }
      if (struct.isSetSqlstate()) {
        optionals.set(1);
      }
      if (struct.isSetDetails()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetVendor_code()) {
        oprot.writeI32(struct.vendor_code);
      }
      if (struct.isSetSqlstate()) {
        oprot.writeString(struct.sqlstate);
      }
      if (struct.isSetDetails()) {
        {
          oprot.writeI32(struct.details.size());
          for (ErrorDetail _iter4 : struct.details)
          {
            _iter4.write(oprot);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, DriverException struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.message = iprot.readString();
      struct.setMessageIsSet(true);
      struct.status_code = StatusCode.findByValue(iprot.readI32());
      struct.setStatus_codeIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.vendor_code = iprot.readI32();
        struct.setVendor_codeIsSet(true);
      }
      if (incoming.get(1)) {
        struct.sqlstate = iprot.readString();
        struct.setSqlstateIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list5 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.details = new java.util.ArrayList<ErrorDetail>(_list5.size);
          @org.apache.thrift.annotation.Nullable ErrorDetail _elem6;
          for (int _i7 = 0; _i7 < _list5.size; ++_i7)
          {
            _elem6 = new ErrorDetail();
            _elem6.read(iprot);
            struct.details.add(_elem6);
          }
        }
        struct.setDetailsIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

