package com.snowflake.jdbc.thrift_gen;
/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)")
public class ExecuteResult implements org.apache.thrift.TBase<ExecuteResult, ExecuteResult._Fields>, java.io.Serializable, Cloneable, Comparable<ExecuteResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ExecuteResult");

  private static final org.apache.thrift.protocol.TField STREAM_FIELD_DESC = new org.apache.thrift.protocol.TField("stream", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField ROWS_AFFECTED_FIELD_DESC = new org.apache.thrift.protocol.TField("rows_affected", org.apache.thrift.protocol.TType.I64, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ExecuteResultStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ExecuteResultTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable ArrowArrayStreamPtr stream; // required
  public long rows_affected; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STREAM((short)1, "stream"),
    ROWS_AFFECTED((short)2, "rows_affected");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STREAM
          return STREAM;
        case 2: // ROWS_AFFECTED
          return ROWS_AFFECTED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ROWS_AFFECTED_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STREAM, new org.apache.thrift.meta_data.FieldMetaData("stream", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ArrowArrayStreamPtr.class)));
    tmpMap.put(_Fields.ROWS_AFFECTED, new org.apache.thrift.meta_data.FieldMetaData("rows_affected", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ExecuteResult.class, metaDataMap);
  }

  public ExecuteResult() {
  }

  public ExecuteResult(
    ArrowArrayStreamPtr stream,
    long rows_affected)
  {
    this();
    this.stream = stream;
    this.rows_affected = rows_affected;
    setRows_affectedIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ExecuteResult(ExecuteResult other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetStream()) {
      this.stream = new ArrowArrayStreamPtr(other.stream);
    }
    this.rows_affected = other.rows_affected;
  }

  @Override
  public ExecuteResult deepCopy() {
    return new ExecuteResult(this);
  }

  @Override
  public void clear() {
    this.stream = null;
    setRows_affectedIsSet(false);
    this.rows_affected = 0;
  }

  @org.apache.thrift.annotation.Nullable
  public ArrowArrayStreamPtr getStream() {
    return this.stream;
  }

  public ExecuteResult setStream(@org.apache.thrift.annotation.Nullable ArrowArrayStreamPtr stream) {
    this.stream = stream;
    return this;
  }

  public void unsetStream() {
    this.stream = null;
  }

  /** Returns true if field stream is set (has been assigned a value) and false otherwise */
  public boolean isSetStream() {
    return this.stream != null;
  }

  public void setStreamIsSet(boolean value) {
    if (!value) {
      this.stream = null;
    }
  }

  public long getRows_affected() {
    return this.rows_affected;
  }

  public ExecuteResult setRows_affected(long rows_affected) {
    this.rows_affected = rows_affected;
    setRows_affectedIsSet(true);
    return this;
  }

  public void unsetRows_affected() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ROWS_AFFECTED_ISSET_ID);
  }

  /** Returns true if field rows_affected is set (has been assigned a value) and false otherwise */
  public boolean isSetRows_affected() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ROWS_AFFECTED_ISSET_ID);
  }

  public void setRows_affectedIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ROWS_AFFECTED_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case STREAM:
      if (value == null) {
        unsetStream();
      } else {
        setStream((ArrowArrayStreamPtr)value);
      }
      break;

    case ROWS_AFFECTED:
      if (value == null) {
        unsetRows_affected();
      } else {
        setRows_affected((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case STREAM:
      return getStream();

    case ROWS_AFFECTED:
      return getRows_affected();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case STREAM:
      return isSetStream();
    case ROWS_AFFECTED:
      return isSetRows_affected();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ExecuteResult)
      return this.equals((ExecuteResult)that);
    return false;
  }

  public boolean equals(ExecuteResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_stream = true && this.isSetStream();
    boolean that_present_stream = true && that.isSetStream();
    if (this_present_stream || that_present_stream) {
      if (!(this_present_stream && that_present_stream))
        return false;
      if (!this.stream.equals(that.stream))
        return false;
    }

    boolean this_present_rows_affected = true;
    boolean that_present_rows_affected = true;
    if (this_present_rows_affected || that_present_rows_affected) {
      if (!(this_present_rows_affected && that_present_rows_affected))
        return false;
      if (this.rows_affected != that.rows_affected)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetStream()) ? 131071 : 524287);
    if (isSetStream())
      hashCode = hashCode * 8191 + stream.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(rows_affected);

    return hashCode;
  }

  @Override
  public int compareTo(ExecuteResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetStream(), other.isSetStream());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStream()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.stream, other.stream);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRows_affected(), other.isSetRows_affected());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRows_affected()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rows_affected, other.rows_affected);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ExecuteResult(");
    boolean first = true;

    sb.append("stream:");
    if (this.stream == null) {
      sb.append("null");
    } else {
      sb.append(this.stream);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("rows_affected:");
    sb.append(this.rows_affected);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (stream == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'stream' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'rows_affected' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
    if (stream != null) {
      stream.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ExecuteResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ExecuteResultStandardScheme getScheme() {
      return new ExecuteResultStandardScheme();
    }
  }

  private static class ExecuteResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<ExecuteResult> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, ExecuteResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STREAM
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.stream = new ArrowArrayStreamPtr();
              struct.stream.read(iprot);
              struct.setStreamIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // ROWS_AFFECTED
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.rows_affected = iprot.readI64();
              struct.setRows_affectedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetRows_affected()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'rows_affected' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, ExecuteResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.stream != null) {
        oprot.writeFieldBegin(STREAM_FIELD_DESC);
        struct.stream.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ROWS_AFFECTED_FIELD_DESC);
      oprot.writeI64(struct.rows_affected);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ExecuteResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public ExecuteResultTupleScheme getScheme() {
      return new ExecuteResultTupleScheme();
    }
  }

  private static class ExecuteResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<ExecuteResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ExecuteResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.stream.write(oprot);
      oprot.writeI64(struct.rows_affected);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ExecuteResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.stream = new ArrowArrayStreamPtr();
      struct.stream.read(iprot);
      struct.setStreamIsSet(true);
      struct.rows_affected = iprot.readI64();
      struct.setRows_affectedIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

