package com.snowflake.jdbc.thrift_gen;
/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)")
public class PartitionedResult implements org.apache.thrift.TBase<PartitionedResult, PartitionedResult._Fields>, java.io.Serializable, Cloneable, Comparable<PartitionedResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("PartitionedResult");

  private static final org.apache.thrift.protocol.TField SCHEMA_FIELD_DESC = new org.apache.thrift.protocol.TField("schema", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField PARTITIONS_FIELD_DESC = new org.apache.thrift.protocol.TField("partitions", org.apache.thrift.protocol.TType.LIST, (short)2);
  private static final org.apache.thrift.protocol.TField ROWS_AFFECTED_FIELD_DESC = new org.apache.thrift.protocol.TField("rows_affected", org.apache.thrift.protocol.TType.I64, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new PartitionedResultStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new PartitionedResultTupleSchemeFactory();

  public long schema; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.nio.ByteBuffer> partitions; // required
  public long rows_affected; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SCHEMA((short)1, "schema"),
    PARTITIONS((short)2, "partitions"),
    ROWS_AFFECTED((short)3, "rows_affected");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SCHEMA
          return SCHEMA;
        case 2: // PARTITIONS
          return PARTITIONS;
        case 3: // ROWS_AFFECTED
          return ROWS_AFFECTED;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SCHEMA_ISSET_ID = 0;
  private static final int __ROWS_AFFECTED_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SCHEMA, new org.apache.thrift.meta_data.FieldMetaData("schema", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.PARTITIONS, new org.apache.thrift.meta_data.FieldMetaData("partitions", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING            , true))));
    tmpMap.put(_Fields.ROWS_AFFECTED, new org.apache.thrift.meta_data.FieldMetaData("rows_affected", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(PartitionedResult.class, metaDataMap);
  }

  public PartitionedResult() {
  }

  public PartitionedResult(
    long schema,
    java.util.List<java.nio.ByteBuffer> partitions,
    long rows_affected)
  {
    this();
    this.schema = schema;
    setSchemaIsSet(true);
    this.partitions = partitions;
    this.rows_affected = rows_affected;
    setRows_affectedIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PartitionedResult(PartitionedResult other) {
    __isset_bitfield = other.__isset_bitfield;
    this.schema = other.schema;
    if (other.isSetPartitions()) {
      java.util.List<java.nio.ByteBuffer> __this__partitions = new java.util.ArrayList<java.nio.ByteBuffer>(other.partitions);
      this.partitions = __this__partitions;
    }
    this.rows_affected = other.rows_affected;
  }

  @Override
  public PartitionedResult deepCopy() {
    return new PartitionedResult(this);
  }

  @Override
  public void clear() {
    setSchemaIsSet(false);
    this.schema = 0;
    this.partitions = null;
    setRows_affectedIsSet(false);
    this.rows_affected = 0;
  }

  public long getSchema() {
    return this.schema;
  }

  public PartitionedResult setSchema(long schema) {
    this.schema = schema;
    setSchemaIsSet(true);
    return this;
  }

  public void unsetSchema() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SCHEMA_ISSET_ID);
  }

  /** Returns true if field schema is set (has been assigned a value) and false otherwise */
  public boolean isSetSchema() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SCHEMA_ISSET_ID);
  }

  public void setSchemaIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SCHEMA_ISSET_ID, value);
  }

  public int getPartitionsSize() {
    return (this.partitions == null) ? 0 : this.partitions.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.nio.ByteBuffer> getPartitionsIterator() {
    return (this.partitions == null) ? null : this.partitions.iterator();
  }

  public void addToPartitions(java.nio.ByteBuffer elem) {
    if (this.partitions == null) {
      this.partitions = new java.util.ArrayList<java.nio.ByteBuffer>();
    }
    this.partitions.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.nio.ByteBuffer> getPartitions() {
    return this.partitions;
  }

  public PartitionedResult setPartitions(@org.apache.thrift.annotation.Nullable java.util.List<java.nio.ByteBuffer> partitions) {
    this.partitions = partitions;
    return this;
  }

  public void unsetPartitions() {
    this.partitions = null;
  }

  /** Returns true if field partitions is set (has been assigned a value) and false otherwise */
  public boolean isSetPartitions() {
    return this.partitions != null;
  }

  public void setPartitionsIsSet(boolean value) {
    if (!value) {
      this.partitions = null;
    }
  }

  public long getRows_affected() {
    return this.rows_affected;
  }

  public PartitionedResult setRows_affected(long rows_affected) {
    this.rows_affected = rows_affected;
    setRows_affectedIsSet(true);
    return this;
  }

  public void unsetRows_affected() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ROWS_AFFECTED_ISSET_ID);
  }

  /** Returns true if field rows_affected is set (has been assigned a value) and false otherwise */
  public boolean isSetRows_affected() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ROWS_AFFECTED_ISSET_ID);
  }

  public void setRows_affectedIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ROWS_AFFECTED_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case SCHEMA:
      if (value == null) {
        unsetSchema();
      } else {
        setSchema((java.lang.Long)value);
      }
      break;

    case PARTITIONS:
      if (value == null) {
        unsetPartitions();
      } else {
        setPartitions((java.util.List<java.nio.ByteBuffer>)value);
      }
      break;

    case ROWS_AFFECTED:
      if (value == null) {
        unsetRows_affected();
      } else {
        setRows_affected((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case SCHEMA:
      return getSchema();

    case PARTITIONS:
      return getPartitions();

    case ROWS_AFFECTED:
      return getRows_affected();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case SCHEMA:
      return isSetSchema();
    case PARTITIONS:
      return isSetPartitions();
    case ROWS_AFFECTED:
      return isSetRows_affected();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof PartitionedResult)
      return this.equals((PartitionedResult)that);
    return false;
  }

  public boolean equals(PartitionedResult that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_schema = true;
    boolean that_present_schema = true;
    if (this_present_schema || that_present_schema) {
      if (!(this_present_schema && that_present_schema))
        return false;
      if (this.schema != that.schema)
        return false;
    }

    boolean this_present_partitions = true && this.isSetPartitions();
    boolean that_present_partitions = true && that.isSetPartitions();
    if (this_present_partitions || that_present_partitions) {
      if (!(this_present_partitions && that_present_partitions))
        return false;
      if (!this.partitions.equals(that.partitions))
        return false;
    }

    boolean this_present_rows_affected = true;
    boolean that_present_rows_affected = true;
    if (this_present_rows_affected || that_present_rows_affected) {
      if (!(this_present_rows_affected && that_present_rows_affected))
        return false;
      if (this.rows_affected != that.rows_affected)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(schema);

    hashCode = hashCode * 8191 + ((isSetPartitions()) ? 131071 : 524287);
    if (isSetPartitions())
      hashCode = hashCode * 8191 + partitions.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(rows_affected);

    return hashCode;
  }

  @Override
  public int compareTo(PartitionedResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetSchema(), other.isSetSchema());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSchema()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.schema, other.schema);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPartitions(), other.isSetPartitions());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPartitions()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.partitions, other.partitions);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRows_affected(), other.isSetRows_affected());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRows_affected()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.rows_affected, other.rows_affected);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("PartitionedResult(");
    boolean first = true;

    sb.append("schema:");
    sb.append(this.schema);
    first = false;
    if (!first) sb.append(", ");
    sb.append("partitions:");
    if (this.partitions == null) {
      sb.append("null");
    } else {
      org.apache.thrift.TBaseHelper.toString(this.partitions, sb);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("rows_affected:");
    sb.append(this.rows_affected);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'schema' because it's a primitive and you chose the non-beans generator.
    if (partitions == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'partitions' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'rows_affected' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PartitionedResultStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PartitionedResultStandardScheme getScheme() {
      return new PartitionedResultStandardScheme();
    }
  }

  private static class PartitionedResultStandardScheme extends org.apache.thrift.scheme.StandardScheme<PartitionedResult> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, PartitionedResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SCHEMA
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.schema = iprot.readI64();
              struct.setSchemaIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PARTITIONS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.partitions = new java.util.ArrayList<java.nio.ByteBuffer>(_list8.size);
                @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = iprot.readBinary();
                  struct.partitions.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setPartitionsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // ROWS_AFFECTED
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.rows_affected = iprot.readI64();
              struct.setRows_affectedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetSchema()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'schema' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetRows_affected()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'rows_affected' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, PartitionedResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(SCHEMA_FIELD_DESC);
      oprot.writeI64(struct.schema);
      oprot.writeFieldEnd();
      if (struct.partitions != null) {
        oprot.writeFieldBegin(PARTITIONS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.partitions.size()));
          for (java.nio.ByteBuffer _iter11 : struct.partitions)
          {
            oprot.writeBinary(_iter11);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ROWS_AFFECTED_FIELD_DESC);
      oprot.writeI64(struct.rows_affected);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PartitionedResultTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public PartitionedResultTupleScheme getScheme() {
      return new PartitionedResultTupleScheme();
    }
  }

  private static class PartitionedResultTupleScheme extends org.apache.thrift.scheme.TupleScheme<PartitionedResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, PartitionedResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI64(struct.schema);
      {
        oprot.writeI32(struct.partitions.size());
        for (java.nio.ByteBuffer _iter12 : struct.partitions)
        {
          oprot.writeBinary(_iter12);
        }
      }
      oprot.writeI64(struct.rows_affected);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, PartitionedResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.schema = iprot.readI64();
      struct.setSchemaIsSet(true);
      {
        org.apache.thrift.protocol.TList _list13 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
        struct.partitions = new java.util.ArrayList<java.nio.ByteBuffer>(_list13.size);
        @org.apache.thrift.annotation.Nullable java.nio.ByteBuffer _elem14;
        for (int _i15 = 0; _i15 < _list13.size; ++_i15)
        {
          _elem14 = iprot.readBinary();
          struct.partitions.add(_elem14);
        }
      }
      struct.setPartitionsIsSet(true);
      struct.rows_affected = iprot.readI64();
      struct.setRows_affectedIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

