package com.snowflake.jdbc.thrift_gen;
/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)")
public enum StatusCode implements org.apache.thrift.TEnum {
  OK(0),
  AUTHENTICATION_ERROR(1),
  NOT_IMPLEMENTED(2),
  NOT_FOUND(3),
  ALREADY_EXISTS(4),
  INVALID_ARGUMENT(5),
  INVALID_STATE(6),
  INVALID_DATA(7),
  IO(8),
  CANCELLED(9),
  UNAUTHENTICATED(10),
  UNAUTHORIZED(11),
  GENERIC_ERROR(12),
  INTERNAL_ERROR(13),
  MISSING_PARAMETER(14),
  INVALID_PARAMETER_VALUE(15),
  LOGIN_ERROR(16);

  private final int value;

  private StatusCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  @Override
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static StatusCode findByValue(int value) { 
    switch (value) {
      case 0:
        return OK;
      case 1:
        return AUTHENTICATION_ERROR;
      case 2:
        return NOT_IMPLEMENTED;
      case 3:
        return NOT_FOUND;
      case 4:
        return ALREADY_EXISTS;
      case 5:
        return INVALID_ARGUMENT;
      case 6:
        return INVALID_STATE;
      case 7:
        return INVALID_DATA;
      case 8:
        return IO;
      case 9:
        return CANCELLED;
      case 10:
        return UNAUTHENTICATED;
      case 11:
        return UNAUTHORIZED;
      case 12:
        return GENERIC_ERROR;
      case 13:
        return INTERNAL_ERROR;
      case 14:
        return MISSING_PARAMETER;
      case 15:
        return INVALID_PARAMETER_VALUE;
      case 16:
        return LOGIN_ERROR;
      default:
        return null;
    }
  }
}
