package com.snowflake.jdbc.thrift_gen;
/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
/**
 * Minimal TLS configuration passed from clients to the core.
 */
@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.22.0)")
public class TlsConfig implements org.apache.thrift.TBase<TlsConfig, TlsConfig._Fields>, java.io.Serializable, Cloneable, Comparable<TlsConfig> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("TlsConfig");

  private static final org.apache.thrift.protocol.TField CUSTOM_ROOT_STORE_PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("custom_root_store_path", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField VERIFY_HOSTNAME_FIELD_DESC = new org.apache.thrift.protocol.TField("verify_hostname", org.apache.thrift.protocol.TType.BOOL, (short)2);
  private static final org.apache.thrift.protocol.TField VERIFY_CERTIFICATES_FIELD_DESC = new org.apache.thrift.protocol.TField("verify_certificates", org.apache.thrift.protocol.TType.BOOL, (short)3);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new TlsConfigStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new TlsConfigTupleSchemeFactory();

  /**
   * Optional path to a PEM bundle of root CAs to trust.
   */
  public @org.apache.thrift.annotation.Nullable java.lang.String custom_root_store_path; // optional
  /**
   * Whether to verify hostnames; defaults to true if unset.
   */
  public boolean verify_hostname; // optional
  /**
   * Whether to verify certificates; defaults to true if unset.
   */
  public boolean verify_certificates; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * Optional path to a PEM bundle of root CAs to trust.
     */
    CUSTOM_ROOT_STORE_PATH((short)1, "custom_root_store_path"),
    /**
     * Whether to verify hostnames; defaults to true if unset.
     */
    VERIFY_HOSTNAME((short)2, "verify_hostname"),
    /**
     * Whether to verify certificates; defaults to true if unset.
     */
    VERIFY_CERTIFICATES((short)3, "verify_certificates");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CUSTOM_ROOT_STORE_PATH
          return CUSTOM_ROOT_STORE_PATH;
        case 2: // VERIFY_HOSTNAME
          return VERIFY_HOSTNAME;
        case 3: // VERIFY_CERTIFICATES
          return VERIFY_CERTIFICATES;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    @Override
    public short getThriftFieldId() {
      return _thriftId;
    }

    @Override
    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __VERIFY_HOSTNAME_ISSET_ID = 0;
  private static final int __VERIFY_CERTIFICATES_ISSET_ID = 1;
  private byte __isset_bitfield = 0;
  private static final _Fields[] optionals = {_Fields.CUSTOM_ROOT_STORE_PATH,_Fields.VERIFY_HOSTNAME,_Fields.VERIFY_CERTIFICATES};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CUSTOM_ROOT_STORE_PATH, new org.apache.thrift.meta_data.FieldMetaData("custom_root_store_path", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.VERIFY_HOSTNAME, new org.apache.thrift.meta_data.FieldMetaData("verify_hostname", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.VERIFY_CERTIFICATES, new org.apache.thrift.meta_data.FieldMetaData("verify_certificates", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(TlsConfig.class, metaDataMap);
  }

  public TlsConfig() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public TlsConfig(TlsConfig other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetCustom_root_store_path()) {
      this.custom_root_store_path = other.custom_root_store_path;
    }
    this.verify_hostname = other.verify_hostname;
    this.verify_certificates = other.verify_certificates;
  }

  @Override
  public TlsConfig deepCopy() {
    return new TlsConfig(this);
  }

  @Override
  public void clear() {
    this.custom_root_store_path = null;
    setVerify_hostnameIsSet(false);
    this.verify_hostname = false;
    setVerify_certificatesIsSet(false);
    this.verify_certificates = false;
  }

  /**
   * Optional path to a PEM bundle of root CAs to trust.
   */
  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCustom_root_store_path() {
    return this.custom_root_store_path;
  }

  /**
   * Optional path to a PEM bundle of root CAs to trust.
   */
  public TlsConfig setCustom_root_store_path(@org.apache.thrift.annotation.Nullable java.lang.String custom_root_store_path) {
    this.custom_root_store_path = custom_root_store_path;
    return this;
  }

  public void unsetCustom_root_store_path() {
    this.custom_root_store_path = null;
  }

  /** Returns true if field custom_root_store_path is set (has been assigned a value) and false otherwise */
  public boolean isSetCustom_root_store_path() {
    return this.custom_root_store_path != null;
  }

  public void setCustom_root_store_pathIsSet(boolean value) {
    if (!value) {
      this.custom_root_store_path = null;
    }
  }

  /**
   * Whether to verify hostnames; defaults to true if unset.
   */
  public boolean isVerify_hostname() {
    return this.verify_hostname;
  }

  /**
   * Whether to verify hostnames; defaults to true if unset.
   */
  public TlsConfig setVerify_hostname(boolean verify_hostname) {
    this.verify_hostname = verify_hostname;
    setVerify_hostnameIsSet(true);
    return this;
  }

  public void unsetVerify_hostname() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VERIFY_HOSTNAME_ISSET_ID);
  }

  /** Returns true if field verify_hostname is set (has been assigned a value) and false otherwise */
  public boolean isSetVerify_hostname() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VERIFY_HOSTNAME_ISSET_ID);
  }

  public void setVerify_hostnameIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VERIFY_HOSTNAME_ISSET_ID, value);
  }

  /**
   * Whether to verify certificates; defaults to true if unset.
   */
  public boolean isVerify_certificates() {
    return this.verify_certificates;
  }

  /**
   * Whether to verify certificates; defaults to true if unset.
   */
  public TlsConfig setVerify_certificates(boolean verify_certificates) {
    this.verify_certificates = verify_certificates;
    setVerify_certificatesIsSet(true);
    return this;
  }

  public void unsetVerify_certificates() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VERIFY_CERTIFICATES_ISSET_ID);
  }

  /** Returns true if field verify_certificates is set (has been assigned a value) and false otherwise */
  public boolean isSetVerify_certificates() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VERIFY_CERTIFICATES_ISSET_ID);
  }

  public void setVerify_certificatesIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VERIFY_CERTIFICATES_ISSET_ID, value);
  }

  @Override
  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case CUSTOM_ROOT_STORE_PATH:
      if (value == null) {
        unsetCustom_root_store_path();
      } else {
        setCustom_root_store_path((java.lang.String)value);
      }
      break;

    case VERIFY_HOSTNAME:
      if (value == null) {
        unsetVerify_hostname();
      } else {
        setVerify_hostname((java.lang.Boolean)value);
      }
      break;

    case VERIFY_CERTIFICATES:
      if (value == null) {
        unsetVerify_certificates();
      } else {
        setVerify_certificates((java.lang.Boolean)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CUSTOM_ROOT_STORE_PATH:
      return getCustom_root_store_path();

    case VERIFY_HOSTNAME:
      return isVerify_hostname();

    case VERIFY_CERTIFICATES:
      return isVerify_certificates();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  @Override
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CUSTOM_ROOT_STORE_PATH:
      return isSetCustom_root_store_path();
    case VERIFY_HOSTNAME:
      return isSetVerify_hostname();
    case VERIFY_CERTIFICATES:
      return isSetVerify_certificates();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof TlsConfig)
      return this.equals((TlsConfig)that);
    return false;
  }

  public boolean equals(TlsConfig that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_custom_root_store_path = true && this.isSetCustom_root_store_path();
    boolean that_present_custom_root_store_path = true && that.isSetCustom_root_store_path();
    if (this_present_custom_root_store_path || that_present_custom_root_store_path) {
      if (!(this_present_custom_root_store_path && that_present_custom_root_store_path))
        return false;
      if (!this.custom_root_store_path.equals(that.custom_root_store_path))
        return false;
    }

    boolean this_present_verify_hostname = true && this.isSetVerify_hostname();
    boolean that_present_verify_hostname = true && that.isSetVerify_hostname();
    if (this_present_verify_hostname || that_present_verify_hostname) {
      if (!(this_present_verify_hostname && that_present_verify_hostname))
        return false;
      if (this.verify_hostname != that.verify_hostname)
        return false;
    }

    boolean this_present_verify_certificates = true && this.isSetVerify_certificates();
    boolean that_present_verify_certificates = true && that.isSetVerify_certificates();
    if (this_present_verify_certificates || that_present_verify_certificates) {
      if (!(this_present_verify_certificates && that_present_verify_certificates))
        return false;
      if (this.verify_certificates != that.verify_certificates)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetCustom_root_store_path()) ? 131071 : 524287);
    if (isSetCustom_root_store_path())
      hashCode = hashCode * 8191 + custom_root_store_path.hashCode();

    hashCode = hashCode * 8191 + ((isSetVerify_hostname()) ? 131071 : 524287);
    if (isSetVerify_hostname())
      hashCode = hashCode * 8191 + ((verify_hostname) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetVerify_certificates()) ? 131071 : 524287);
    if (isSetVerify_certificates())
      hashCode = hashCode * 8191 + ((verify_certificates) ? 131071 : 524287);

    return hashCode;
  }

  @Override
  public int compareTo(TlsConfig other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetCustom_root_store_path(), other.isSetCustom_root_store_path());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCustom_root_store_path()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.custom_root_store_path, other.custom_root_store_path);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetVerify_hostname(), other.isSetVerify_hostname());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVerify_hostname()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.verify_hostname, other.verify_hostname);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetVerify_certificates(), other.isSetVerify_certificates());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVerify_certificates()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.verify_certificates, other.verify_certificates);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  @Override
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  @Override
  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  @Override
  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("TlsConfig(");
    boolean first = true;

    if (isSetCustom_root_store_path()) {
      sb.append("custom_root_store_path:");
      if (this.custom_root_store_path == null) {
        sb.append("null");
      } else {
        sb.append(this.custom_root_store_path);
      }
      first = false;
    }
    if (isSetVerify_hostname()) {
      if (!first) sb.append(", ");
      sb.append("verify_hostname:");
      sb.append(this.verify_hostname);
      first = false;
    }
    if (isSetVerify_certificates()) {
      if (!first) sb.append(", ");
      sb.append("verify_certificates:");
      sb.append(this.verify_certificates);
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class TlsConfigStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TlsConfigStandardScheme getScheme() {
      return new TlsConfigStandardScheme();
    }
  }

  private static class TlsConfigStandardScheme extends org.apache.thrift.scheme.StandardScheme<TlsConfig> {

    @Override
    public void read(org.apache.thrift.protocol.TProtocol iprot, TlsConfig struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CUSTOM_ROOT_STORE_PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.custom_root_store_path = iprot.readString();
              struct.setCustom_root_store_pathIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // VERIFY_HOSTNAME
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.verify_hostname = iprot.readBool();
              struct.setVerify_hostnameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // VERIFY_CERTIFICATES
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.verify_certificates = iprot.readBool();
              struct.setVerify_certificatesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    @Override
    public void write(org.apache.thrift.protocol.TProtocol oprot, TlsConfig struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.custom_root_store_path != null) {
        if (struct.isSetCustom_root_store_path()) {
          oprot.writeFieldBegin(CUSTOM_ROOT_STORE_PATH_FIELD_DESC);
          oprot.writeString(struct.custom_root_store_path);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetVerify_hostname()) {
        oprot.writeFieldBegin(VERIFY_HOSTNAME_FIELD_DESC);
        oprot.writeBool(struct.verify_hostname);
        oprot.writeFieldEnd();
      }
      if (struct.isSetVerify_certificates()) {
        oprot.writeFieldBegin(VERIFY_CERTIFICATES_FIELD_DESC);
        oprot.writeBool(struct.verify_certificates);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class TlsConfigTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    @Override
    public TlsConfigTupleScheme getScheme() {
      return new TlsConfigTupleScheme();
    }
  }

  private static class TlsConfigTupleScheme extends org.apache.thrift.scheme.TupleScheme<TlsConfig> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, TlsConfig struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetCustom_root_store_path()) {
        optionals.set(0);
      }
      if (struct.isSetVerify_hostname()) {
        optionals.set(1);
      }
      if (struct.isSetVerify_certificates()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetCustom_root_store_path()) {
        oprot.writeString(struct.custom_root_store_path);
      }
      if (struct.isSetVerify_hostname()) {
        oprot.writeBool(struct.verify_hostname);
      }
      if (struct.isSetVerify_certificates()) {
        oprot.writeBool(struct.verify_certificates);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, TlsConfig struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        struct.custom_root_store_path = iprot.readString();
        struct.setCustom_root_store_pathIsSet(true);
      }
      if (incoming.get(1)) {
        struct.verify_hostname = iprot.readBool();
        struct.setVerify_hostnameIsSet(true);
      }
      if (incoming.get(2)) {
        struct.verify_certificates = iprot.readBool();
        struct.setVerify_certificatesIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

