[package]
name = "nodejs_bridge"
version = "0.0.1"
edition = "2024"
publish = false

[lib]
name = "nodejs_bridge"
crate-type = ["cdylib"]

[dependencies]
sf_core = { path = "../sf_core" }
napi = { version = "3", default-features = false, features = ["napi9"] }
napi-derive = "3"

[build-dependencies]
napi-build = "2"
