[package]
name = "nodejs_bridge"
version = "0.0.1"
edition = "2024"
publish = false

[lib]
name = "nodejs_bridge"
crate-type = ["cdylib"]

[dependencies]
sf_core = { path = "../sf_core" }
napi = { version = "3", default-features = false, features = ["napi9", "async"] }
napi-derive = "3"
arrow = { version = ">=54.0.0, <59" }
snafu = "0.8.7"
tracing-subscriber = { version = "0.3.19", features = ["fmt", "env-filter"] }
tracing = "0.1.41"

[build-dependencies]
napi-build = "2"
