[package]
name = "python_bridge"
version = "0.1.0"
edition = "2024"

[lib]
name = "sf_core_python"
crate-type = ["cdylib", "rlib"]

[features]
default = ["extension-module"]
extension-module = ["pyo3/extension-module"]
vendored-openssl = ["sf_core/vendored-openssl"]

[dependencies]
sf_core = { path = "../sf_core" }
proto_utils = { path = "../proto_utils" }
pyo3 = { version = "0.29.0" }
pyo3-async-runtimes = { version = "0.29", features = ["tokio-runtime"] }
tokio = { version = "1.50.0", features = ["rt-multi-thread"] }
tokio-util = "0.7"
futures = "0.3"
tracing = "0.1.41"
