using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Snowflake.Data.Tests.ArchitectureInvariantTests.Metadata;

namespace Snowflake.Data.Tests.ArchitectureInvariantTests.Utils;

public static class AssemblyUtil
{
    internal static string SolutionRoot { get; } = FindSolutionRoot();

    internal static IEnumerable<(string RelativePath, SyntaxNode Root)> GetSyntaxRoots(Metadata.AssemblyMetadata assemblyMetadata)
    {
        var assemblyName = assemblyMetadata.ProjectName;
        var path = assemblyName.Contains("Tests")
            ? Path.Combine(SolutionRoot, "tests", assemblyName)
            : Path.Combine(SolutionRoot, "src", assemblyName);
        var csFiles = Directory.GetFiles(path, "*.cs", SearchOption.AllDirectories)
            .Where(x => !x.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}"));

        foreach (var file in csFiles)
        {
            var source = File.ReadAllText(file);

            // Skip auto-generated files
            if (source.StartsWith("// <auto-generated>", StringComparison.Ordinal))
                continue;

            var tree = CSharpSyntaxTree.ParseText(source, path: file);
            var root = tree.GetRoot();
            var relativePath = file.Substring(path.Length + 1);

            yield return (relativePath, root);
        }
    }

    internal static Assembly LoadAssembly(Metadata.AssemblyMetadata assemblyMetadata)
    {
        if (Equals(assemblyMetadata, AssembliesMetadata.RegressionTestsAssembly))
        {
            var path = Path.Combine(SolutionRoot, $"tests{Path.DirectorySeparatorChar}{AssembliesMetadata.RegressionTestsAssembly.Name}");
            var files = Directory.GetFiles(path, $"{AssembliesMetadata.RegressionTestsAssembly.Name}.dll", SearchOption.AllDirectories);
            var platform = Environment.Version.Major.ToString();
            var dllFile = files.First(x => x.Contains(platform));
            return Assembly.LoadFrom(dllFile);
        }

        return Assembly.Load(new AssemblyName(assemblyMetadata));
    }

    private static string FindSolutionRoot()
    {
        var dir = AppContext.BaseDirectory;
        while (dir != null)
        {
            if (File.Exists(Path.Combine(dir, "Snowflake.Data.sln")))
                return dir;

            dir = dir.EndsWith($"{Path.DirectorySeparatorChar}dotnet")
                ? null
                : Directory.GetParent(dir)?.FullName;
        }

        throw new InvalidOperationException("Cannot find solution root directory");
    }
}
