using System.Reflection;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Snowflake.Data.Tests.ArchitectureInvariantTests.Metadata;
using Snowflake.Data.Tests.Compatibility;
using AssemblyMetadata = Snowflake.Data.Tests.ArchitectureInvariantTests.Metadata.AssemblyMetadata;

namespace Snowflake.Data.Tests.ArchitectureInvariantTests.Utils;

public static class AssemblyUtil
{
    internal static string SolutionRoot { get; } = FindSolutionRoot();

    internal static IEnumerable<(string RelativePath, SyntaxNode Root)> GetSyntaxRoots(Metadata.AssemblyMetadata assemblyMetadata)
    {
        var assemblyName = assemblyMetadata.ProjectName;
        var path = assemblyName.Contains("Tests")
            ? Path.Combine(SolutionRoot, "tests", assemblyName)
            : Path.Combine(SolutionRoot, "src", assemblyName);
        var csFiles = Directory.GetFiles(path, "*.cs", SearchOption.AllDirectories)
            .Where(x => !x.Contains($"{Path.DirectorySeparatorChar}obj{Path.DirectorySeparatorChar}"));

        foreach (var file in csFiles)
        {
            var source = File.ReadAllText(file);

            // Skip auto-generated files
            if (source.StartsWith("// <auto-generated>", StringComparison.Ordinal))
                continue;

            var tree = CSharpSyntaxTree.ParseText(source, path: file);
            var root = tree.GetRoot();
            var relativePath = file.Substring(path.Length + 1);

            yield return (relativePath, root);
        }
    }

    internal static Assembly LoadAssembly(AssemblyMetadata assemblyMetadata)
    {
        if (TryLoadAs(assemblyMetadata, AssembliesMetadata.RegressionTestsAssembly, out var loadFrom))
            return loadFrom!;
        if (TryLoadAs(assemblyMetadata, AssembliesMetadata.InteropTestsAssembly, out loadFrom))
            return loadFrom!;

        return Assembly.Load(new AssemblyName(assemblyMetadata));
    }

    private static bool TryLoadAs(AssemblyMetadata assemblyMetadata, AssemblyMetadata asTarget, out Assembly? result)
    {
        if (!Equals(assemblyMetadata.ToString(), asTarget.ToString()))
        {
            result = null;
            return false;
        }

        var path = Path.Combine(SolutionRoot, $"tests{Path.DirectorySeparatorChar}{asTarget}");
        var files = Directory.GetFiles(path, $"{asTarget}.dll", SearchOption.AllDirectories);
        var platform = Environment.Version.Major.ToString();
        var dllFile = files.FirstOrDefault(x => x.Contains(platform));

        if (dllFile == null)
        {
#if NETFRAMEWORK
            Skip.When(true, "Different versions of .net framework might not be able to load type system properly");
#else
            dllFile = files.First();
#endif
        }

        result = Assembly.LoadFrom(dllFile!);
        return true;
    }

    private static string FindSolutionRoot()
    {
        var dir = AppContext.BaseDirectory;
        while (dir != null)
        {
            if (File.Exists(Path.Combine(dir, "Snowflake.Data.sln")))
                return dir;

            dir = dir.EndsWith($"{Path.DirectorySeparatorChar}dotnet")
                ? null
                : Directory.GetParent(dir)?.FullName;
        }

        throw new InvalidOperationException("Cannot find solution root directory");
    }
}
