// <auto-generated>
//   This file was generated by proto_generator. Do not edit manually.
// </auto-generated>

namespace Snowflake.Data.Proto;

/// <summary>
/// Service interface for DatabaseDriver.
/// </summary>
internal interface IDatabaseDriverService
{
    DatabaseNewResponse DatabaseNew(DatabaseNewRequest request);

    Task<DatabaseNewResponse> DatabaseNewAsync(
        DatabaseNewRequest request,
        CancellationToken cancellationToken);

    DatabaseSetOptionsResponse DatabaseSetOptions(DatabaseSetOptionsRequest request);

    Task<DatabaseSetOptionsResponse> DatabaseSetOptionsAsync(
        DatabaseSetOptionsRequest request,
        CancellationToken cancellationToken);

    DatabaseInitResponse DatabaseInit(DatabaseInitRequest request);

    Task<DatabaseInitResponse> DatabaseInitAsync(
        DatabaseInitRequest request,
        CancellationToken cancellationToken);

    DatabaseReleaseResponse DatabaseRelease(DatabaseReleaseRequest request);

    Task<DatabaseReleaseResponse> DatabaseReleaseAsync(
        DatabaseReleaseRequest request,
        CancellationToken cancellationToken);

    DatabaseFetchChunkResponse DatabaseFetchChunk(DatabaseFetchChunkRequest request);

    Task<DatabaseFetchChunkResponse> DatabaseFetchChunkAsync(
        DatabaseFetchChunkRequest request,
        CancellationToken cancellationToken);

    ConnectionNewResponse ConnectionNew(ConnectionNewRequest request);

    Task<ConnectionNewResponse> ConnectionNewAsync(
        ConnectionNewRequest request,
        CancellationToken cancellationToken);

    ConnectionSetOptionsResponse ConnectionSetOptions(ConnectionSetOptionsRequest request);

    Task<ConnectionSetOptionsResponse> ConnectionSetOptionsAsync(
        ConnectionSetOptionsRequest request,
        CancellationToken cancellationToken);

    ConnectionInitResponse ConnectionInit(ConnectionInitRequest request);

    Task<ConnectionInitResponse> ConnectionInitAsync(
        ConnectionInitRequest request,
        CancellationToken cancellationToken);

    ConnectionReleaseResponse ConnectionRelease(ConnectionReleaseRequest request);

    Task<ConnectionReleaseResponse> ConnectionReleaseAsync(
        ConnectionReleaseRequest request,
        CancellationToken cancellationToken);

    ConnectionCloseResponse ConnectionClose(ConnectionCloseRequest request);

    Task<ConnectionCloseResponse> ConnectionCloseAsync(
        ConnectionCloseRequest request,
        CancellationToken cancellationToken);

    ConnectionIsClosedResponse ConnectionIsClosed(ConnectionIsClosedRequest request);

    Task<ConnectionIsClosedResponse> ConnectionIsClosedAsync(
        ConnectionIsClosedRequest request,
        CancellationToken cancellationToken);

    ConnectionGetInfoResponse ConnectionGetInfo(ConnectionGetInfoRequest request);

    Task<ConnectionGetInfoResponse> ConnectionGetInfoAsync(
        ConnectionGetInfoRequest request,
        CancellationToken cancellationToken);

    ConnectionGetObjectsResponse ConnectionGetObjects(ConnectionGetObjectsRequest request);

    Task<ConnectionGetObjectsResponse> ConnectionGetObjectsAsync(
        ConnectionGetObjectsRequest request,
        CancellationToken cancellationToken);

    ConnectionGetTableSchemaResponse ConnectionGetTableSchema(ConnectionGetTableSchemaRequest request);

    Task<ConnectionGetTableSchemaResponse> ConnectionGetTableSchemaAsync(
        ConnectionGetTableSchemaRequest request,
        CancellationToken cancellationToken);

    ConnectionGetTableTypesResponse ConnectionGetTableTypes(ConnectionGetTableTypesRequest request);

    Task<ConnectionGetTableTypesResponse> ConnectionGetTableTypesAsync(
        ConnectionGetTableTypesRequest request,
        CancellationToken cancellationToken);

    ConnectionCommitResponse ConnectionCommit(ConnectionCommitRequest request);

    Task<ConnectionCommitResponse> ConnectionCommitAsync(
        ConnectionCommitRequest request,
        CancellationToken cancellationToken);

    ConnectionRollbackResponse ConnectionRollback(ConnectionRollbackRequest request);

    Task<ConnectionRollbackResponse> ConnectionRollbackAsync(
        ConnectionRollbackRequest request,
        CancellationToken cancellationToken);

    ConnectionSetAutocommitResponse ConnectionSetAutocommit(ConnectionSetAutocommitRequest request);

    Task<ConnectionSetAutocommitResponse> ConnectionSetAutocommitAsync(
        ConnectionSetAutocommitRequest request,
        CancellationToken cancellationToken);

    ConnectionUseDatabaseResponse ConnectionUseDatabase(ConnectionUseDatabaseRequest request);

    Task<ConnectionUseDatabaseResponse> ConnectionUseDatabaseAsync(
        ConnectionUseDatabaseRequest request,
        CancellationToken cancellationToken);

    ConnectionUseSchemaResponse ConnectionUseSchema(ConnectionUseSchemaRequest request);

    Task<ConnectionUseSchemaResponse> ConnectionUseSchemaAsync(
        ConnectionUseSchemaRequest request,
        CancellationToken cancellationToken);

    ConnectionSetSessionParametersResponse ConnectionSetSessionParameters(ConnectionSetSessionParametersRequest request);

    Task<ConnectionSetSessionParametersResponse> ConnectionSetSessionParametersAsync(
        ConnectionSetSessionParametersRequest request,
        CancellationToken cancellationToken);

    ConnectionGetParameterResponse ConnectionGetParameter(ConnectionGetParameterRequest request);

    Task<ConnectionGetParameterResponse> ConnectionGetParameterAsync(
        ConnectionGetParameterRequest request,
        CancellationToken cancellationToken);

    ConnectionGetAllParametersResponse ConnectionGetAllParameters(ConnectionGetAllParametersRequest request);

    Task<ConnectionGetAllParametersResponse> ConnectionGetAllParametersAsync(
        ConnectionGetAllParametersRequest request,
        CancellationToken cancellationToken);

    ConnectionGetServerVersionResponse ConnectionGetServerVersion(ConnectionGetServerVersionRequest request);

    Task<ConnectionGetServerVersionResponse> ConnectionGetServerVersionAsync(
        ConnectionGetServerVersionRequest request,
        CancellationToken cancellationToken);

    ConnectionValidateOptionsResponse ConnectionValidateOptions(ConnectionValidateOptionsRequest request);

    Task<ConnectionValidateOptionsResponse> ConnectionValidateOptionsAsync(
        ConnectionValidateOptionsRequest request,
        CancellationToken cancellationToken);

    ExecuteQueryResponse ConnectionGetQueryResult(ConnectionGetQueryResultRequest request);

    Task<ExecuteQueryResponse> ConnectionGetQueryResultAsync(
        ConnectionGetQueryResultRequest request,
        CancellationToken cancellationToken);

    ResultSetResponse ConnectionGetResultSet(ConnectionGetResultSetRequest request);

    Task<ResultSetResponse> ConnectionGetResultSetAsync(
        ConnectionGetResultSetRequest request,
        CancellationToken cancellationToken);

    ConnectionGetQueryStatusResponse ConnectionGetQueryStatus(ConnectionGetQueryStatusRequest request);

    Task<ConnectionGetQueryStatusResponse> ConnectionGetQueryStatusAsync(
        ConnectionGetQueryStatusRequest request,
        CancellationToken cancellationToken);

    ConnectionAbortQueryResponse ConnectionAbortQuery(ConnectionAbortQueryRequest request);

    Task<ConnectionAbortQueryResponse> ConnectionAbortQueryAsync(
        ConnectionAbortQueryRequest request,
        CancellationToken cancellationToken);

    ConnectionSendHttpResponse ConnectionSendHttp(ConnectionSendHttpRequest request);

    Task<ConnectionSendHttpResponse> ConnectionSendHttpAsync(
        ConnectionSendHttpRequest request,
        CancellationToken cancellationToken);

    ConnectionTokenResponse ConnectionRequestToken(ConnectionTokenRequest request);

    Task<ConnectionTokenResponse> ConnectionRequestTokenAsync(
        ConnectionTokenRequest request,
        CancellationToken cancellationToken);

    ConnectionHeartbeatResponse ConnectionHeartbeat(ConnectionHeartbeatRequest request);

    Task<ConnectionHeartbeatResponse> ConnectionHeartbeatAsync(
        ConnectionHeartbeatRequest request,
        CancellationToken cancellationToken);

    StatementNewResponse StatementNew(StatementNewRequest request);

    Task<StatementNewResponse> StatementNewAsync(
        StatementNewRequest request,
        CancellationToken cancellationToken);

    StatementReleaseResponse StatementRelease(StatementReleaseRequest request);

    Task<StatementReleaseResponse> StatementReleaseAsync(
        StatementReleaseRequest request,
        CancellationToken cancellationToken);

    StatementSetSqlQueryResponse StatementSetSqlQuery(StatementSetSqlQueryRequest request);

    Task<StatementSetSqlQueryResponse> StatementSetSqlQueryAsync(
        StatementSetSqlQueryRequest request,
        CancellationToken cancellationToken);

    StatementSetSubstraitPlanResponse StatementSetSubstraitPlan(StatementSetSubstraitPlanRequest request);

    Task<StatementSetSubstraitPlanResponse> StatementSetSubstraitPlanAsync(
        StatementSetSubstraitPlanRequest request,
        CancellationToken cancellationToken);

    StatementPrepareResponse StatementPrepare(StatementPrepareRequest request);

    Task<StatementPrepareResponse> StatementPrepareAsync(
        StatementPrepareRequest request,
        CancellationToken cancellationToken);

    StatementSetOptionsResponse StatementSetOptions(StatementSetOptionsRequest request);

    Task<StatementSetOptionsResponse> StatementSetOptionsAsync(
        StatementSetOptionsRequest request,
        CancellationToken cancellationToken);

    StatementGetParameterSchemaResponse StatementGetParameterSchema(StatementGetParameterSchemaRequest request);

    Task<StatementGetParameterSchemaResponse> StatementGetParameterSchemaAsync(
        StatementGetParameterSchemaRequest request,
        CancellationToken cancellationToken);

    ExecuteQueryResponse StatementExecuteQuery(StatementExecuteQueryRequest request);

    Task<ExecuteQueryResponse> StatementExecuteQueryAsync(
        StatementExecuteQueryRequest request,
        CancellationToken cancellationToken);

    StatementExecutePartitionsResponse StatementExecutePartitions(StatementExecutePartitionsRequest request);

    Task<StatementExecutePartitionsResponse> StatementExecutePartitionsAsync(
        StatementExecutePartitionsRequest request,
        CancellationToken cancellationToken);

    StatementReadPartitionResponse StatementReadPartition(StatementReadPartitionRequest request);

    Task<StatementReadPartitionResponse> StatementReadPartitionAsync(
        StatementReadPartitionRequest request,
        CancellationToken cancellationToken);

    StatementExecuteAsyncResponse StatementExecuteAsync(StatementExecuteAsyncRequest request);

    Task<StatementExecuteAsyncResponse> StatementExecuteAsyncAsync(
        StatementExecuteAsyncRequest request,
        CancellationToken cancellationToken);

    ResultSetGetStreamResponse ResultSetGetStream(ResultSetGetStreamRequest request);

    Task<ResultSetGetStreamResponse> ResultSetGetStreamAsync(
        ResultSetGetStreamRequest request,
        CancellationToken cancellationToken);

    ResultSetGetChunksResponse ResultSetGetChunks(ResultSetGetChunksRequest request);

    Task<ResultSetGetChunksResponse> ResultSetGetChunksAsync(
        ResultSetGetChunksRequest request,
        CancellationToken cancellationToken);

    ResultSetReleaseResponse ResultSetRelease(ResultSetReleaseRequest request);

    Task<ResultSetReleaseResponse> ResultSetReleaseAsync(
        ResultSetReleaseRequest request,
        CancellationToken cancellationToken);

    ConfigLoadAllSectionsResponse ConfigLoadAllSections(ConfigLoadAllSectionsRequest request);

    Task<ConfigLoadAllSectionsResponse> ConfigLoadAllSectionsAsync(
        ConfigLoadAllSectionsRequest request,
        CancellationToken cancellationToken);

    ConfigGetPathsResponse ConfigGetPaths(ConfigGetPathsRequest request);

    Task<ConfigGetPathsResponse> ConfigGetPathsAsync(
        ConfigGetPathsRequest request,
        CancellationToken cancellationToken);

    TelemetrySendResponse TelemetrySendApiUsage(TelemetrySendApiUsageRequest request);

    Task<TelemetrySendResponse> TelemetrySendApiUsageAsync(
        TelemetrySendApiUsageRequest request,
        CancellationToken cancellationToken);

    TelemetrySendResponse TelemetrySendWrapperError(TelemetrySendWrapperErrorRequest request);

    Task<TelemetrySendResponse> TelemetrySendWrapperErrorAsync(
        TelemetrySendWrapperErrorRequest request,
        CancellationToken cancellationToken);

}
