// <auto-generated>
//   This file was generated by proto_generator. Do not edit manually.
// </auto-generated>

using Google.Protobuf;

namespace Snowflake.Data.Proto;

/// <summary>
/// Client implementation for DatabaseDriver.
/// Dispatches protobuf-serialized requests via <see cref="ICoreTransport"/>.
/// </summary>
internal sealed class DatabaseDriverServiceClient : IDatabaseDriverService
{
    private readonly ICoreTransport _transport;

    public DatabaseDriverServiceClient(ICoreTransport transport)
    {
        _transport = transport;
    }

    /// <inheritdoc />
    public DatabaseNewResponse DatabaseNew(DatabaseNewRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "database_new", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                DatabaseNewResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<DatabaseNewResponse> DatabaseNewAsync(
        DatabaseNewRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "database_new", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                DatabaseNewResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public DatabaseSetOptionsResponse DatabaseSetOptions(DatabaseSetOptionsRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "database_set_options", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                DatabaseSetOptionsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<DatabaseSetOptionsResponse> DatabaseSetOptionsAsync(
        DatabaseSetOptionsRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "database_set_options", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                DatabaseSetOptionsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public DatabaseInitResponse DatabaseInit(DatabaseInitRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "database_init", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                DatabaseInitResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<DatabaseInitResponse> DatabaseInitAsync(
        DatabaseInitRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "database_init", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                DatabaseInitResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public DatabaseReleaseResponse DatabaseRelease(DatabaseReleaseRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "database_release", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                DatabaseReleaseResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<DatabaseReleaseResponse> DatabaseReleaseAsync(
        DatabaseReleaseRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "database_release", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                DatabaseReleaseResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public DatabaseFetchChunkResponse DatabaseFetchChunk(DatabaseFetchChunkRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "database_fetch_chunk", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                DatabaseFetchChunkResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<DatabaseFetchChunkResponse> DatabaseFetchChunkAsync(
        DatabaseFetchChunkRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "database_fetch_chunk", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                DatabaseFetchChunkResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionNewResponse ConnectionNew(ConnectionNewRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_new", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionNewResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionNewResponse> ConnectionNewAsync(
        ConnectionNewRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_new", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionNewResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionSetOptionsResponse ConnectionSetOptions(ConnectionSetOptionsRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_set_options", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionSetOptionsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionSetOptionsResponse> ConnectionSetOptionsAsync(
        ConnectionSetOptionsRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_set_options", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionSetOptionsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionInitResponse ConnectionInit(ConnectionInitRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_init", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionInitResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionInitResponse> ConnectionInitAsync(
        ConnectionInitRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_init", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionInitResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionReleaseResponse ConnectionRelease(ConnectionReleaseRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_release", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionReleaseResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionReleaseResponse> ConnectionReleaseAsync(
        ConnectionReleaseRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_release", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionReleaseResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionCloseResponse ConnectionClose(ConnectionCloseRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_close", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionCloseResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionCloseResponse> ConnectionCloseAsync(
        ConnectionCloseRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_close", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionCloseResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionIsClosedResponse ConnectionIsClosed(ConnectionIsClosedRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_is_closed", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionIsClosedResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionIsClosedResponse> ConnectionIsClosedAsync(
        ConnectionIsClosedRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_is_closed", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionIsClosedResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionGetInfoResponse ConnectionGetInfo(ConnectionGetInfoRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_get_info", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetInfoResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionGetInfoResponse> ConnectionGetInfoAsync(
        ConnectionGetInfoRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_get_info", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetInfoResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionGetObjectsResponse ConnectionGetObjects(ConnectionGetObjectsRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_get_objects", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetObjectsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionGetObjectsResponse> ConnectionGetObjectsAsync(
        ConnectionGetObjectsRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_get_objects", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetObjectsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionGetTableSchemaResponse ConnectionGetTableSchema(ConnectionGetTableSchemaRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_get_table_schema", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetTableSchemaResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionGetTableSchemaResponse> ConnectionGetTableSchemaAsync(
        ConnectionGetTableSchemaRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_get_table_schema", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetTableSchemaResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionGetTableTypesResponse ConnectionGetTableTypes(ConnectionGetTableTypesRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_get_table_types", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetTableTypesResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionGetTableTypesResponse> ConnectionGetTableTypesAsync(
        ConnectionGetTableTypesRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_get_table_types", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetTableTypesResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionCommitResponse ConnectionCommit(ConnectionCommitRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_commit", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionCommitResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionCommitResponse> ConnectionCommitAsync(
        ConnectionCommitRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_commit", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionCommitResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionRollbackResponse ConnectionRollback(ConnectionRollbackRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_rollback", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionRollbackResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionRollbackResponse> ConnectionRollbackAsync(
        ConnectionRollbackRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_rollback", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionRollbackResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionSetAutocommitResponse ConnectionSetAutocommit(ConnectionSetAutocommitRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_set_autocommit", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionSetAutocommitResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionSetAutocommitResponse> ConnectionSetAutocommitAsync(
        ConnectionSetAutocommitRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_set_autocommit", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionSetAutocommitResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionUseDatabaseResponse ConnectionUseDatabase(ConnectionUseDatabaseRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_use_database", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionUseDatabaseResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionUseDatabaseResponse> ConnectionUseDatabaseAsync(
        ConnectionUseDatabaseRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_use_database", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionUseDatabaseResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionUseSchemaResponse ConnectionUseSchema(ConnectionUseSchemaRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_use_schema", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionUseSchemaResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionUseSchemaResponse> ConnectionUseSchemaAsync(
        ConnectionUseSchemaRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_use_schema", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionUseSchemaResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionSetSessionParametersResponse ConnectionSetSessionParameters(ConnectionSetSessionParametersRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_set_session_parameters", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionSetSessionParametersResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionSetSessionParametersResponse> ConnectionSetSessionParametersAsync(
        ConnectionSetSessionParametersRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_set_session_parameters", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionSetSessionParametersResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionGetParameterResponse ConnectionGetParameter(ConnectionGetParameterRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_get_parameter", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetParameterResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionGetParameterResponse> ConnectionGetParameterAsync(
        ConnectionGetParameterRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_get_parameter", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetParameterResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionGetAllParametersResponse ConnectionGetAllParameters(ConnectionGetAllParametersRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_get_all_parameters", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetAllParametersResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionGetAllParametersResponse> ConnectionGetAllParametersAsync(
        ConnectionGetAllParametersRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_get_all_parameters", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetAllParametersResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionGetServerVersionResponse ConnectionGetServerVersion(ConnectionGetServerVersionRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_get_server_version", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetServerVersionResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionGetServerVersionResponse> ConnectionGetServerVersionAsync(
        ConnectionGetServerVersionRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_get_server_version", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetServerVersionResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionValidateOptionsResponse ConnectionValidateOptions(ConnectionValidateOptionsRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_validate_options", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionValidateOptionsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionValidateOptionsResponse> ConnectionValidateOptionsAsync(
        ConnectionValidateOptionsRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_validate_options", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionValidateOptionsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ExecuteQueryResponse ConnectionGetQueryResult(ConnectionGetQueryResultRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_get_query_result", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ExecuteQueryResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ExecuteQueryResponse> ConnectionGetQueryResultAsync(
        ConnectionGetQueryResultRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_get_query_result", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ExecuteQueryResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ResultSetResponse ConnectionGetResultSet(ConnectionGetResultSetRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_get_result_set", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ResultSetResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ResultSetResponse> ConnectionGetResultSetAsync(
        ConnectionGetResultSetRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_get_result_set", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ResultSetResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionGetQueryStatusResponse ConnectionGetQueryStatus(ConnectionGetQueryStatusRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_get_query_status", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetQueryStatusResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionGetQueryStatusResponse> ConnectionGetQueryStatusAsync(
        ConnectionGetQueryStatusRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_get_query_status", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionGetQueryStatusResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionAbortQueryResponse ConnectionAbortQuery(ConnectionAbortQueryRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_abort_query", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionAbortQueryResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionAbortQueryResponse> ConnectionAbortQueryAsync(
        ConnectionAbortQueryRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_abort_query", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionAbortQueryResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionSendHttpResponse ConnectionSendHttp(ConnectionSendHttpRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_send_http", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionSendHttpResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionSendHttpResponse> ConnectionSendHttpAsync(
        ConnectionSendHttpRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_send_http", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionSendHttpResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionTokenResponse ConnectionRequestToken(ConnectionTokenRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_request_token", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionTokenResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionTokenResponse> ConnectionRequestTokenAsync(
        ConnectionTokenRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_request_token", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionTokenResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConnectionHeartbeatResponse ConnectionHeartbeat(ConnectionHeartbeatRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "connection_heartbeat", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionHeartbeatResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConnectionHeartbeatResponse> ConnectionHeartbeatAsync(
        ConnectionHeartbeatRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "connection_heartbeat", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConnectionHeartbeatResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public StatementNewResponse StatementNew(StatementNewRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "statement_new", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementNewResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<StatementNewResponse> StatementNewAsync(
        StatementNewRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "statement_new", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementNewResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public StatementReleaseResponse StatementRelease(StatementReleaseRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "statement_release", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementReleaseResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<StatementReleaseResponse> StatementReleaseAsync(
        StatementReleaseRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "statement_release", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementReleaseResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public StatementSetSqlQueryResponse StatementSetSqlQuery(StatementSetSqlQueryRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "statement_set_sql_query", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementSetSqlQueryResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<StatementSetSqlQueryResponse> StatementSetSqlQueryAsync(
        StatementSetSqlQueryRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "statement_set_sql_query", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementSetSqlQueryResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public StatementSetSubstraitPlanResponse StatementSetSubstraitPlan(StatementSetSubstraitPlanRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "statement_set_substrait_plan", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementSetSubstraitPlanResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<StatementSetSubstraitPlanResponse> StatementSetSubstraitPlanAsync(
        StatementSetSubstraitPlanRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "statement_set_substrait_plan", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementSetSubstraitPlanResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public StatementPrepareResponse StatementPrepare(StatementPrepareRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "statement_prepare", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementPrepareResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<StatementPrepareResponse> StatementPrepareAsync(
        StatementPrepareRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "statement_prepare", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementPrepareResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public StatementSetOptionsResponse StatementSetOptions(StatementSetOptionsRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "statement_set_options", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementSetOptionsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<StatementSetOptionsResponse> StatementSetOptionsAsync(
        StatementSetOptionsRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "statement_set_options", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementSetOptionsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public StatementGetParameterSchemaResponse StatementGetParameterSchema(StatementGetParameterSchemaRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "statement_get_parameter_schema", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementGetParameterSchemaResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<StatementGetParameterSchemaResponse> StatementGetParameterSchemaAsync(
        StatementGetParameterSchemaRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "statement_get_parameter_schema", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementGetParameterSchemaResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ExecuteQueryResponse StatementExecuteQuery(StatementExecuteQueryRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "statement_execute_query", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ExecuteQueryResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ExecuteQueryResponse> StatementExecuteQueryAsync(
        StatementExecuteQueryRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "statement_execute_query", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ExecuteQueryResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public StatementExecutePartitionsResponse StatementExecutePartitions(StatementExecutePartitionsRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "statement_execute_partitions", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementExecutePartitionsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<StatementExecutePartitionsResponse> StatementExecutePartitionsAsync(
        StatementExecutePartitionsRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "statement_execute_partitions", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementExecutePartitionsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public StatementReadPartitionResponse StatementReadPartition(StatementReadPartitionRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "statement_read_partition", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementReadPartitionResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<StatementReadPartitionResponse> StatementReadPartitionAsync(
        StatementReadPartitionRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "statement_read_partition", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementReadPartitionResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public StatementExecuteAsyncResponse StatementExecuteAsync(StatementExecuteAsyncRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "statement_execute_async", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementExecuteAsyncResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<StatementExecuteAsyncResponse> StatementExecuteAsyncAsync(
        StatementExecuteAsyncRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "statement_execute_async", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                StatementExecuteAsyncResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ResultSetGetStreamResponse ResultSetGetStream(ResultSetGetStreamRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "result_set_get_stream", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ResultSetGetStreamResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ResultSetGetStreamResponse> ResultSetGetStreamAsync(
        ResultSetGetStreamRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "result_set_get_stream", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ResultSetGetStreamResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ResultSetGetChunksResponse ResultSetGetChunks(ResultSetGetChunksRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "result_set_get_chunks", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ResultSetGetChunksResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ResultSetGetChunksResponse> ResultSetGetChunksAsync(
        ResultSetGetChunksRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "result_set_get_chunks", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ResultSetGetChunksResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ResultSetReleaseResponse ResultSetRelease(ResultSetReleaseRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "result_set_release", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ResultSetReleaseResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ResultSetReleaseResponse> ResultSetReleaseAsync(
        ResultSetReleaseRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "result_set_release", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ResultSetReleaseResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConfigLoadAllSectionsResponse ConfigLoadAllSections(ConfigLoadAllSectionsRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "config_load_all_sections", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConfigLoadAllSectionsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConfigLoadAllSectionsResponse> ConfigLoadAllSectionsAsync(
        ConfigLoadAllSectionsRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "config_load_all_sections", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConfigLoadAllSectionsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public ConfigGetPathsResponse ConfigGetPaths(ConfigGetPathsRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "config_get_paths", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConfigGetPathsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<ConfigGetPathsResponse> ConfigGetPathsAsync(
        ConfigGetPathsRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "config_get_paths", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                ConfigGetPathsResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public TelemetrySendResponse TelemetrySendApiUsage(TelemetrySendApiUsageRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "telemetry_send_api_usage", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                TelemetrySendResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<TelemetrySendResponse> TelemetrySendApiUsageAsync(
        TelemetrySendApiUsageRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "telemetry_send_api_usage", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                TelemetrySendResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public TelemetrySendResponse TelemetrySendWrapperError(TelemetrySendWrapperErrorRequest request)
    {
        var response = _transport.HandleMessage(
            "DatabaseDriver", "telemetry_send_wrapper_error", request.ToByteArray());
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                TelemetrySendResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

    /// <inheritdoc />
    public async Task<TelemetrySendResponse> TelemetrySendWrapperErrorAsync(
        TelemetrySendWrapperErrorRequest request,
        CancellationToken cancellationToken = default)
    {
        var response = await _transport.HandleMessageAsync(
            "DatabaseDriver", "telemetry_send_wrapper_error", request.ToByteArray(),
            cancellationToken).ConfigureAwait(false);
        return response.Code switch
        {
            TransportResponse.CodeSuccess =>
                TelemetrySendResponse.Parser.ParseFrom(response.ResponseBytes),
            TransportResponse.CodeApplicationError =>
                throw new ServiceException(
                    DriverException.Parser.ParseFrom(response.ResponseBytes)),
            _ => throw new TransportException(
                System.Text.Encoding.UTF8.GetString(response.ResponseBytes)),
        };
    }

}
