name: Build ODBC Packages

# Builds every distributable ODBC artifact
on:
  push:
    branches:
      - 'release/odbc-**'
  pull_request:
    paths:
      - 'odbc/installer/**'
      - 'ci/Dockerfile.rocky-rpm-build'
      - '.github/actions/install-wix-from-artifact/**'
      - '.github/workflows/build-odbc-packages.yml'
      - '.github/workflows/_build-odbc-packages.yml'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_odbc_packages:
    uses: ./.github/workflows/_build-odbc-packages.yml
